"""
Migrations for the Voyant Scraper Django app.

This package contains database migration files generated by Django,
which manage changes to the database schema for the `voyant.scraper` application.
"""