# Generated by Django 6.0.2 on 2026-09-09 12:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Pipeline name (unique per tenant)", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Human-readable description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Pipeline lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cron expression for scheduled execution (empty = manual only)",
                        max_length=128,
                    ),
                ),
                (
                    "schedule_timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for the schedule expression",
                        max_length=64,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Global pipeline configuration (default params, retry policy, etc.)",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Auto-incrementing version for pipeline changes",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Soft-deletion timestamp (null = active)",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "voyant_pipeline",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="idx_pipe_tenant_status"
                    ),
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="idx_pipe_tenant_created",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant_id", "name"),
                        name="uq_pipeline_name_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        default="queued",
                        help_text="Run status",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User or system that triggered this run",
                        max_length=256,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("schedule", "Schedule"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this run was triggered",
                        max_length=32,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Runtime parameters for this execution",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When execution started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When execution completed (success or failure)",
                        null=True,
                    ),
                ),
                (
                    "logs",
                    models.TextField(
                        blank=True, default="", help_text="Aggregated execution logs"
                    ),
                ),
                (
                    "result_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of execution results (rows processed, errors, etc.)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if the run failed",
                    ),
                ),
                (
                    "steps_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of steps completed"
                    ),
                ),
                (
                    "steps_total",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of steps in the pipeline"
                    ),
                ),
                (
                    "temporal_workflow_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Temporal workflow ID for tracking",
                        max_length=256,
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        help_text="Pipeline being executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="pipelines.pipeline",
                    ),
                ),
            ],
            options={
                "db_table": "voyant_pipeline_run",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PipelineStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("ingest", "Ingest"),
                            ("transform", "Transform"),
                            ("quality_check", "Quality Check"),
                            ("profile", "Profile"),
                            ("export", "Export"),
                            ("scrape", "Scrape"),
                            ("sql_query", "SQL Query"),
                            ("custom", "Custom"),
                        ],
                        help_text="Type of operation this step performs",
                        max_length=32,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable step name",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Execution order (lower runs first)"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Step-specific configuration (parameters, selectors, queries, etc.)",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of retries on failure"
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=300, help_text="Maximum execution time in seconds"
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Steps that must complete before this one starts",
                        related_name="dependents",
                        to="pipelines.pipelinestep",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        help_text="Parent pipeline",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="pipelines.pipeline",
                    ),
                ),
            ],
            options={
                "db_table": "voyant_pipeline_step",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PipelineStepRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "output_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Step output (result data, artifact references, etc.)",
                    ),
                ),
                ("logs", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "attempt",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Execution attempt number (incremented on retry)",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        help_text="Parent pipeline run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_runs",
                        to="pipelines.pipelinerun",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="Pipeline step being executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="pipelines.pipelinestep",
                    ),
                ),
            ],
            options={
                "db_table": "voyant_pipeline_step_run",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["pipeline_id", "-created_at"], name="idx_run_pipeline_created"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["tenant_id", "status"], name="idx_run_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestep",
            index=models.Index(
                fields=["pipeline_id", "order"], name="idx_step_pipeline_order"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinesteprun",
            index=models.Index(
                fields=["pipeline_run_id", "step_id"], name="idx_steprun_run_step"
            ),
        ),
    ]
