# Generated by Django 5.0.6 on 2026-05-22 09:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LineageNode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "urn",
                    models.CharField(
                        db_index=True,
                        help_text="Unique resource name (URN) for this node",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the node", max_length=255
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("dataset", "Dataset"),
                            ("transformation", "Transformation"),
                            ("model", "ML Model"),
                            ("report", "Report"),
                            ("api", "API Endpoint"),
                        ],
                        db_index=True,
                        default="dataset",
                        help_text="Type of lineage node",
                        max_length=32,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        help_text="Platform or system where this node exists",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the node"),
                ),
                (
                    "upstream_urns",
                    models.JSONField(
                        default=list, help_text="List of URNs for upstream dependencies"
                    ),
                ),
                (
                    "downstream_urns",
                    models.JSONField(
                        default=list, help_text="List of URNs for downstream consumers"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata about the node"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lineage Node",
                "verbose_name_plural": "Lineage Nodes",
                "db_table": "voyant_lineage_node",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the policy", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the policy"
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("access_control", "Access Control"),
                            ("data_retention", "Data Retention"),
                            ("data_quality", "Data Quality"),
                            ("compliance", "Compliance"),
                            ("usage", "Usage Policy"),
                        ],
                        db_index=True,
                        default="access_control",
                        help_text="Type of governance policy",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the policy",
                        max_length=16,
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        default=dict,
                        help_text="Policy rules and conditions in JSON format",
                    ),
                ),
                (
                    "scope",
                    models.JSONField(
                        default=dict,
                        help_text="Scope definition (datasets, users, operations)",
                    ),
                ),
                (
                    "enforcement_level",
                    models.CharField(
                        default="strict",
                        help_text="Enforcement level: strict, warn, or audit",
                        max_length=32,
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        help_text="Owner or team responsible for this policy",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata about the policy"
                    ),
                ),
            ],
            options={
                "verbose_name": "Governance Policy",
                "verbose_name_plural": "Governance Policies",
                "db_table": "voyant_policy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotaTier",
            fields=[
                (
                    "tier_id",
                    models.CharField(
                        help_text="Unique identifier for the tier",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the tier", max_length=128
                    ),
                ),
                (
                    "max_jobs_per_day",
                    models.IntegerField(
                        default=100, help_text="Maximum number of jobs per day"
                    ),
                ),
                (
                    "max_artifacts_gb",
                    models.FloatField(
                        default=10.0, help_text="Maximum artifact storage in GB"
                    ),
                ),
                (
                    "max_sources",
                    models.IntegerField(
                        default=10, help_text="Maximum number of data sources"
                    ),
                ),
                (
                    "max_concurrent_jobs",
                    models.IntegerField(
                        default=5, help_text="Maximum concurrent running jobs"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional tier metadata"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the tier was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the tier was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quota Tier",
                "verbose_name_plural": "Quota Tiers",
                "db_table": "voyant_quota_tier",
                "ordering": ["tier_id"],
            },
        ),
        migrations.CreateModel(
            name="TenantQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "jobs_today",
                    models.IntegerField(
                        default=0, help_text="Number of jobs executed today"
                    ),
                ),
                (
                    "artifacts_gb",
                    models.FloatField(
                        default=0.0, help_text="Current artifact storage usage in GB"
                    ),
                ),
                (
                    "sources_count",
                    models.IntegerField(
                        default=0, help_text="Current number of data sources"
                    ),
                ),
                (
                    "concurrent_jobs",
                    models.IntegerField(
                        default=0, help_text="Current number of concurrent running jobs"
                    ),
                ),
                (
                    "last_reset_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Last time daily counters were reset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Quota",
                "verbose_name_plural": "Tenant Quotas",
                "db_table": "voyant_tenant_quota",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataContract",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the data contract",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the contract"
                    ),
                ),
                (
                    "dataset_urn",
                    models.CharField(
                        db_index=True,
                        help_text="DataHub URN for the dataset this contract applies to",
                        max_length=512,
                    ),
                ),
                (
                    "schema_definition",
                    models.JSONField(
                        default=dict,
                        help_text="JSON schema defining expected data structure",
                    ),
                ),
                (
                    "quality_rules",
                    models.JSONField(
                        default=list,
                        help_text="List of data quality rules and constraints",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the contract",
                        max_length=16,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Semantic version of the contract",
                        max_length=32,
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        help_text="Owner or team responsible for this contract",
                        max_length=255,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata about the contract"
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Contract",
                "verbose_name_plural": "Data Contracts",
                "db_table": "voyant_data_contract",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "-created_at"],
                        name="voyant_data_tenant__4bbef6_idx",
                    ),
                    models.Index(
                        fields=["dataset_urn"], name="voyant_data_dataset_b2e6ee_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="datacontract",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "name", "version"),
                name="unique_contract_version_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="lineagenode",
            index=models.Index(
                fields=["tenant_id", "node_type", "-created_at"],
                name="voyant_line_tenant__f5a2e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lineagenode",
            index=models.Index(fields=["urn"], name="voyant_line_urn_4f3d1d_idx"),
        ),
        migrations.AddIndex(
            model_name="lineagenode",
            index=models.Index(
                fields=["platform"], name="voyant_line_platfor_679536_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["tenant_id", "policy_type", "status"],
                name="voyant_poli_tenant__d7f0aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["status", "-created_at"], name="voyant_poli_status_6ef448_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="policy",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "name"), name="unique_policy_name_per_tenant"
            ),
        ),
        migrations.AddField(
            model_name="tenantquota",
            name="tier",
            field=models.ForeignKey(
                help_text="Assigned quota tier",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_quotas",
                to="governance.quotatier",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantquota",
            index=models.Index(
                fields=["tenant_id"], name="voyant_tena_tenant__7af0e7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantquota",
            constraint=models.UniqueConstraint(
                fields=("tenant_id",), name="unique_quota_per_tenant"
            ),
        ),
    ]
