# Generated by Django 5.2.16 on 2026-09-05 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnMaskPolicy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Policy name", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Table this policy applies to", max_length=255
                    ),
                ),
                (
                    "column_name",
                    models.CharField(help_text="Column to mask", max_length=255),
                ),
                (
                    "mask_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Mask (replace with ***)"),
                            ("partial", "Partial Mask (show first/last N chars)"),
                            ("hash", "Hash (SHA-256 of value)"),
                            ("redact", "Redact (replace with [REDACTED])"),
                            ("null", "Null (replace with NULL)"),
                            ("custom", "Custom (apply custom function)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "mask_config",
                    models.JSONField(
                        default=dict,
                        help_text='Mask config: {"show_first": 2, "show_last": 4, "mask_char": "*"}',
                    ),
                ),
                (
                    "applies_to_roles",
                    models.JSONField(
                        default=list,
                        help_text="Roles this mask applies to (empty = all roles)",
                    ),
                ),
                (
                    "exempt_roles",
                    models.JSONField(
                        default=list,
                        help_text='Roles exempt from this mask (e.g. ["hr_admin"])',
                    ),
                ),
            ],
            options={
                "db_table": "governance_column_mask",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "table_name"],
                        name="governance__tenant__812724_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataClassification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Classification name (e.g. 'PII', 'Financial')",
                        max_length=255,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("table", "Table"),
                            ("column", "Column"),
                            ("object_type", "Ontology Object Type"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        help_text="Name of the target (table, column, etc.)",
                        max_length=255,
                    ),
                ),
                ("requires_encryption", models.BooleanField(default=False)),
                ("requires_masking", models.BooleanField(default=False)),
                (
                    "retention_days",
                    models.IntegerField(
                        blank=True, help_text="Data retention period", null=True
                    ),
                ),
            ],
            options={
                "db_table": "governance_classification",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "target_type", "target_name"],
                        name="governance__tenant__1434a9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RowSecurityPolicy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Policy name", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Table this policy applies to", max_length=255
                    ),
                ),
                (
                    "column_name",
                    models.CharField(
                        blank=True,
                        help_text="Column to filter on (optional)",
                        max_length=255,
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("user_match", "User Match (column = current_user)"),
                            ("role_based", "Role-Based (column IN allowed_values)"),
                            ("custom_sql", "Custom SQL Filter"),
                        ],
                        help_text="Type of row filter",
                        max_length=50,
                    ),
                ),
                (
                    "filter_config",
                    models.JSONField(
                        default=dict,
                        help_text='Filter config: {"column": "tenant_id", "role_map": {"admin": ["*"], "analyst": ["dept_a"]}}',
                    ),
                ),
                (
                    "custom_sql",
                    models.TextField(
                        blank=True,
                        help_text="Custom SQL WHERE clause (for custom_sql type)",
                    ),
                ),
                (
                    "applies_to_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Roles this policy applies to: ["analyst", "viewer"]',
                    ),
                ),
                (
                    "applies_to_users",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Specific user IDs this policy applies to",
                    ),
                ),
            ],
            options={
                "db_table": "governance_row_security_policy",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "table_name"],
                        name="governance__tenant__cee22d_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="governance__tenant__fc7dfc_idx",
                    ),
                ],
            },
        ),
    ]
