# Generated by Django 5.2.14 on 2026-09-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0003_add_security_policy_column_mask"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="columnmask",
            new_name="governance__tenant__7fdee2_idx",
            old_name="governance__tenant_mask_tbl_idx",
        ),
        migrations.RenameIndex(
            model_name="securitypolicy",
            new_name="governance__tenant__d84a8e_idx",
            old_name="governance__tenant_sec_tbl_idx",
        ),
        migrations.RenameIndex(
            model_name="securitypolicy",
            new_name="governance__tenant__e3392c_idx",
            old_name="governance__tenant_sec_sts_idx",
        ),
    ]
