# Generated by Django 5.2.14 on 2026-09-09 16:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0004_cell_security_abac"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABACPolicy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique policy name", max_length=255, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "subject_attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Subject attribute conditions: {"roles": ["analyst"], "department": "finance", "clearance_level": {"gte": 3}}',
                    ),
                ),
                (
                    "resource_attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Resource attribute conditions: {"type": "dataset", "classification": ["public", "internal"], "owner_team": "$subject.team"}',
                    ),
                ),
                (
                    "environment_attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Environment attribute conditions: {"time_of_day": {"gte": "08:00", "lte": "18:00"}, "ip_range": "10.0.0.0/8", "day_of_week": ["mon", "tue", "wed", "thu", "fri"]}',
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        default="deny",
                        help_text="Decision when all conditions match",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Lower number = higher priority. Evaluated in ascending order.",
                    ),
                ),
            ],
            options={
                "verbose_name": "ABAC Policy",
                "verbose_name_plural": "ABAC Policies",
                "db_table": "governance_abac_policy",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="governance__tenant__a884fb_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="governance__priorit_4c1f2c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CellSecurityPolicy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Policy name", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        db_index=True,
                        help_text="Fully-qualified table name",
                        max_length=255,
                    ),
                ),
                (
                    "column_name",
                    models.CharField(
                        help_text="Column this policy applies to", max_length=255
                    ),
                ),
                (
                    "row_condition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Row condition as key/value pairs. Values starting with "$viewer." are resolved from viewer attributes. Empty = all rows.',
                    ),
                ),
                (
                    "viewer_condition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Viewer attributes that must match: {"roles": ["analyst"], "department": "finance"}. Empty = all viewers.',
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("mask", "Mask"),
                            ("deny", "Deny"),
                        ],
                        default="mask",
                        help_text="Access decision when conditions match: allow / mask / deny",
                        max_length=10,
                    ),
                ),
                (
                    "mask_value",
                    models.CharField(
                        blank=True,
                        default="***",
                        help_text="Replacement value when decision is MASK",
                        max_length=255,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Lower number = higher priority. First matching policy wins.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cell Security Policy",
                "verbose_name_plural": "Cell Security Policies",
                "db_table": "governance_cell_security_policy",
                "ordering": ["priority", "-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "table_name", "column_name"],
                        name="governance__tenant__359798_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="governance__tenant__5b244f_idx",
                    ),
                ],
            },
        ),
    ]
