[pytest]
DJANGO_SETTINGS_MODULE = voyant_project.settings
python_files = tests.py test_*.py *_tests.py
addopts = --strict-markers --reuse-db
markers =
    integration: mark test as integration test (requires DB/Infra)
    e2e: mark test as end-to-end test (requires full stack)
    slow: mark test as slow
    benchmark: mark test as benchmark
testpaths = tests apps
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
