"""
Intent Engine — Core module with Groq LLM integration.

Translates natural language intent into structured execution plans.
Uses Groq API (OpenAI-compatible) with openai/gpt-oss-120b model.

Architecture:
1. Intent Classifier — classify intent type (query, pipeline, scraper, analyze)
2. Schema Resolver — load tenant's ontology for context
3. Plan Generator — Groq LLM translates intent + schema → structured plan
4. Plan Validator — validate plan against ontology
5. Plan Executor — execute plan via existing tools/workflows
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import Any
from enum import StrEnum

import httpx

from apps.core.config import get_settings

logger = logging.getLogger(__name__)


class IntentType(StrEnum):
    QUERY = "query"
    PIPELINE = "pipeline"
    SCRAPER = "scraper"
    ANALYZE = "analyze"
    UNKNOWN = "unknown"


@dataclass
class IntentPlan:
    """Structured execution plan generated by the intent engine."""

    intent_type: IntentType
    confidence: float
    steps: list[dict[str, Any]]
    assumptions: list[str] = field(default_factory=list)
    cached: bool = False
    raw_llm_response: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "intent_type": self.intent_type.value,
            "confidence": self.confidence,
            "steps": self.steps,
            "assumptions": self.assumptions,
            "cached": self.cached,
        }


# System prompt for the Intent Engine LLM
INTENT_SYSTEM_PROMPT = """You are Voyant's Intent Engine. Your job is to translate natural language
intent into structured JSON execution plans.

You have access to these tools:
- voyant.sql.execute: Execute SQL query (params: sql, limit)
- voyant.analyze: Run analysis (params: source_id, table, analyzers, sample_size)
- voyant.ingest: Ingest data (params: source_id, mode, tables)
- voyant.profile: Profile data (params: source_id, table, sample_size)
- voyant.quality: Quality checks (params: source_id, table, checks)
- voyant.search: Semantic search (params: query, limit)
- scrape.fetch: Fetch web page (params: url, engine, timeout)
- scrape.extract: Extract from HTML (params: html, selectors)
- voyant.scraper.template.run: Run scraper template (params: template_id, parameters)

The user's ontology schema is provided below. Use it to generate correct SQL queries.

OUTPUT FORMAT: Return ONLY valid JSON matching this schema:
{
  "intent_type": "query|pipeline|scraper|analyze",
  "confidence": 0.0-1.0,
  "steps": [
    {"tool": "tool.name", "params": {"key": "value"}}
  ],
  "assumptions": ["list of assumptions made"]
}"""


class IntentEngine:
    """
    Core intent engine with Groq LLM integration.

    Translates natural language into execution plans using Groq's
    openai/gpt-oss-120b model via OpenAI-compatible API.
    """

    def __init__(self):
        self._plan_cache: dict[str, IntentPlan] = {}
        self._settings = get_settings()

    def classify_intent(self, text: str) -> IntentType:
        """Fast keyword-based intent classification (no LLM call)."""
        text_lower = text.lower()

        scraper_keywords = ["scrape", "crawl", "extract from website", "fetch page", "parse html"]
        if any(kw in text_lower for kw in scraper_keywords):
            return IntentType.SCRAPER

        pipeline_keywords = ["pipeline", "etl", "data flow", "transform", "clean", "ingest"]
        if any(kw in text_lower for kw in pipeline_keywords):
            return IntentType.PIPELINE

        analyze_keywords = ["analyze", "anomal", "forecast", "predict", "cluster", "segment", "trend"]
        if any(kw in text_lower for kw in analyze_keywords):
            return IntentType.ANALYZE

        return IntentType.QUERY

    def resolve_schema(self, tenant_id: str) -> dict[str, Any]:
        """Load tenant's ontology for LLM context."""
        try:
            from apps.ontology.models import ObjectType, Property, LinkType

            types = ObjectType.objects.filter(
                tenant_id=tenant_id, deleted_at__isnull=True
            )
            schema: dict[str, Any] = {"object_types": [], "link_types": []}

            for ot in types[:50]:
                props = Property.objects.filter(object_type=ot)
                schema["object_types"].append({
                    "name": ot.name,
                    "description": ot.description,
                    "properties": [
                        {"name": p.name, "type": p.property_type, "required": p.required}
                        for p in props
                    ],
                })

            links = LinkType.objects.filter(
                tenant_id=tenant_id, deleted_at__isnull=True
            )
            for lt in links[:100]:
                schema["link_types"].append({
                    "name": lt.name,
                    "source": lt.source_object_type.name,
                    "target": lt.target_object_type.name,
                    "cardinality": lt.cardinality,
                })

            return schema
        except Exception as exc:
            logger.warning("Failed to resolve schema: %s", exc)
            return {"object_types": [], "link_types": []}

    def generate_plan(
        self,
        intent: str,
        tenant_id: str,
        intent_type: IntentType | None = None,
    ) -> IntentPlan:
        """Generate an execution plan from natural language intent.

        1. Check cache
        2. Classify intent (fast, no LLM)
        3. Resolve schema from ontology
        4. Call Groq LLM for plan generation
        5. Parse and validate plan
        6. Cache result
        """
        # Check cache
        cache_key = f"{tenant_id}:{intent}"
        if self._settings.llm_cache_enabled and cache_key in self._plan_cache:
            cached = self._plan_cache[cache_key]
            cached.cached = True
            return cached

        # 1. Classify
        if intent_type is None:
            intent_type = self.classify_intent(intent)

        # 2. Resolve schema
        schema = self.resolve_schema(tenant_id)

        # 3. Call LLM
        if self._settings.llm_provider == "none" or not self._settings.intent_engine_enabled:
            plan = self._generate_fallback(intent, intent_type, schema, tenant_id)
        else:
            plan = self._call_llm(intent, intent_type, schema, tenant_id)

        # 4. Cache
        if self._settings.llm_cache_enabled:
            self._plan_cache[cache_key] = plan

        return plan

    def _call_llm(
        self,
        intent: str,
        intent_type: IntentType,
        schema: dict[str, Any],
        tenant_id: str,
    ) -> IntentPlan:
        """Call Groq LLM for plan generation."""
        schema_str = json.dumps(schema, indent=2)[:3000]  # Limit context size

        user_message = f"""Intent: {intent}
Intent type: {intent_type.value}
Tenant ID: {tenant_id}

Ontology Schema:
{schema_str}

Generate a JSON execution plan for this intent."""

        try:
            response = httpx.post(
                f"{self._settings.llm_api_url}/chat/completions",
                headers={
                    "Authorization": f"Bearer {self._settings.llm_api_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": self._settings.llm_model,
                    "messages": [
                        {"role": "system", "content": INTENT_SYSTEM_PROMPT},
                        {"role": "user", "content": user_message},
                    ],
                    "temperature": self._settings.llm_temperature,
                    "max_tokens": self._settings.llm_max_tokens,
                    "response_format": {"type": "json_object"},
                },
                timeout=self._settings.llm_timeout_seconds,
            )
            response.raise_for_status()

            data = response.json()
            content = data["choices"][0]["message"]["content"]

            return self._parse_plan(content, intent_type)

        except Exception as exc:
            logger.error("LLM call failed: %s", exc)
            return self._generate_fallback(intent, intent_type, schema, tenant_id)

    def _parse_plan(self, content: str, intent_type: IntentType) -> IntentPlan:
        """Parse LLM JSON response into IntentPlan."""
        try:
            data = json.loads(content)
            return IntentPlan(
                intent_type=IntentType(data.get("intent_type", intent_type.value)),
                confidence=float(data.get("confidence", 0.5)),
                steps=data.get("steps", []),
                assumptions=data.get("assumptions", []),
                raw_llm_response=content,
            )
        except (json.JSONDecodeError, ValueError) as exc:
            logger.warning("Failed to parse LLM response: %s", exc)
            return IntentPlan(
                intent_type=intent_type,
                confidence=0.3,
                steps=[],
                assumptions=[f"LLM response parsing failed: {exc}"],
                raw_llm_response=content,
            )

    def _generate_fallback(
        self,
        intent: str,
        intent_type: IntentType,
        schema: dict[str, Any],
        tenant_id: str,
    ) -> IntentPlan:
        """Generate a plan without LLM (keyword-based fallback)."""
        steps = []
        assumptions = []

        if intent_type == IntentType.QUERY and schema.get("object_types"):
            ot = schema["object_types"][0]
            props = [p["name"] for p in ot.get("properties", [])][:20]
            columns = ", ".join(props) if props else "*"
            steps.append({
                "tool": "voyant.sql.execute",
                "params": {"sql": f"SELECT {columns} FROM {ot['name'].lower()} LIMIT 1000"},
            })
            assumptions.append(f"Fallback: querying {ot['name']}")

        elif intent_type == IntentType.ANALYZE:
            steps.append({"tool": "voyant.analyze", "params": {"analyzers": ["profiling"]}})
            assumptions.append("Fallback: general profiling analysis")

        return IntentPlan(
            intent_type=intent_type,
            confidence=0.3,
            steps=steps,
            assumptions=assumptions,
        )

    def execute_plan(self, plan: IntentPlan, tenant_id: str) -> dict[str, Any]:
        """Execute a validated plan."""
        results = []
        for i, step in enumerate(plan.steps):
            tool = step.get("tool", "")
            params = step.get("params", {})

            try:
                result = self._execute_step(tool, params, tenant_id)
                results.append({"step": i, "tool": tool, "result": result})
            except Exception as exc:
                results.append({"step": i, "tool": tool, "error": str(exc)})

        return {"steps": results, "plan": plan.to_dict()}

    def _execute_step(self, tool: str, params: dict, tenant_id: str) -> dict:
        """Execute a single plan step."""
        if tool == "voyant.sql.execute":
            from apps.core.lib.trino import get_trino_client
            client = get_trino_client()
            result = client.execute(params.get("sql", ""), limit=params.get("limit", 1000))
            return {
                "columns": result.columns,
                "rows": result.rows[:100],
                "row_count": result.row_count,
            }

        elif tool == "voyant.analyze":
            from apps.core.lib.workflow_utils import dispatch_workflow
            from apps.worker.workflows.analyze_workflow import AnalyzeWorkflow
            job = dispatch_workflow(
                workflow_cls=AnalyzeWorkflow,
                job_type="analyze",
                source_id=params.get("source_id", ""),
                parameters=params,
                tenant_id=tenant_id,
            )
            return {"job_id": str(job.job_id), "status": job.status}

        elif tool == "voyant.scraper.template.run":
            from apps.scraper.models import ScrapeTemplate
            template = ScrapeTemplate.objects.filter(id=params.get("template_id")).first()
            if not template:
                return {"error": "Template not found"}
            return {"template": template.name, "status": "dispatched"}

        else:
            return {"status": "skipped", "reason": f"Unknown tool: {tool}"}


# Singleton
_engine: IntentEngine | None = None


def get_intent_engine() -> IntentEngine:
    """Get the singleton intent engine."""
    global _engine
    if _engine is None:
        _engine = IntentEngine()
    return _engine
