# Milvus standalone config override
etcd:
  endpoints:
    - voyant_etcd:2379
minio:
  address: minio
  port: 9000
  useSSL: false
  bucketName: a-bucket
  useIAM: false
  cloudProvider: aws
  useVirtualHost: false
  requestTimeoutMs: 10000
