"""Notifications — Django ORM models.

Provides Notification and NotificationPreference models for the in-app
notification center with multi-channel dispatch support.
"""

from __future__ import annotations

from django.db import models
from django.utils import timezone as tz

from apps.core.models import TenantModel, UUIDModel


class Notification(TenantModel, UUIDModel):
    """
    A user-scoped notification generated by system events or manual creation.
    """

    class NotificationType(models.TextChoices):
        INFORMATION = "information", "Information"
        WARNING = "warning", "Warning"
        ERROR = "error", "Error"
        SUCCESS = "success", "Success"

    user_id = models.CharField(
        max_length=256,
        db_index=True,
        help_text="Recipient user identifier",
    )
    type = models.CharField(
        max_length=20,
        choices=NotificationType.choices,
        default=NotificationType.INFORMATION,
        db_index=True,
        help_text="Notification severity/type",
    )
    title = models.CharField(
        max_length=255,
        help_text="Short notification title",
    )
    message = models.TextField(
        help_text="Full notification body",
    )
    resource_type = models.CharField(
        max_length=64,
        blank=True,
        default="",
        db_index=True,
        help_text="Type of related resource (e.g. 'job', 'pipeline')",
    )
    resource_id = models.CharField(
        max_length=256,
        blank=True,
        default="",
        db_index=True,
        help_text="Identifier of the related resource",
    )
    is_read = models.BooleanField(
        default=False,
        db_index=True,
        help_text="Whether the user has read this notification",
    )
    read_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Timestamp when the notification was marked as read",
    )

    class Meta(TenantModel.Meta, UUIDModel.Meta):  # type: ignore[reportIncompatibleVariableOverride]
        db_table = "voyant_notification"
        verbose_name = "Notification"
        verbose_name_plural = "Notifications"
        ordering = ["-created_at"]
        indexes = [
            models.Index(
                fields=["tenant_id", "user_id", "is_read"],
                name="idx_notif_tenant_user_read",
            ),
            models.Index(
                fields=["tenant_id", "user_id", "-created_at"],
                name="idx_notif_tenant_user_time",
            ),
        ]

    def __str__(self) -> str:
        return f"[{self.type}] {self.title} → {self.user_id}"

    def mark_read(self) -> None:
        """Mark this notification as read."""
        if not self.is_read:
            self.is_read = True
            self.read_at = tz.now()
            self.save(update_fields=["is_read", "read_at", "updated_at"])


class NotificationPreference(TenantModel, UUIDModel):
    """
    Per-user notification preference controlling delivery channels for events.
    """

    class Channel(models.TextChoices):
        IN_APP = "in_app", "In-App"
        EMAIL = "email", "Email"
        SLACK = "slack", "Slack"

    user_id = models.CharField(
        max_length=256,
        db_index=True,
        help_text="User identifier",
    )
    event_type = models.CharField(
        max_length=128,
        db_index=True,
        help_text="Event type this preference applies to (e.g. 'job.completed')",
    )
    channel = models.CharField(
        max_length=20,
        choices=Channel.choices,
        default=Channel.IN_APP,
        help_text="Delivery channel",
    )
    enabled = models.BooleanField(
        default=True,
        help_text="Whether notifications for this event+channel are enabled",
    )

    class Meta(TenantModel.Meta, UUIDModel.Meta):  # type: ignore[reportIncompatibleVariableOverride]
        db_table = "voyant_notification_preference"
        verbose_name = "Notification Preference"
        verbose_name_plural = "Notification Preferences"
        unique_together = [("tenant_id", "user_id", "event_type", "channel")]

    def __str__(self) -> str:
        status = "enabled" if self.enabled else "disabled"
        return f"{self.user_id} / {self.event_type} / {self.channel} ({status})"
