# Generated by Django 5.0.6 on 2026-05-22 09:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique setting key (e.g., 'max_concurrent_jobs')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Setting value (stored as text, cast based on value_type)"
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        help_text="Data type of the value",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of the setting",
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this setting contains sensitive data",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the setting was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
                "db_table": "voyant_system_setting",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        help_text="User or service that performed the action",
                        max_length=256,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Action performed (e.g., 'job.created', 'data.accessed')",
                        max_length=128,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of resource affected (e.g., 'job', 'source')",
                        max_length=64,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier of the affected resource",
                        max_length=256,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("denied", "Denied"),
                        ],
                        db_index=True,
                        help_text="Outcome of the action",
                        max_length=32,
                    ),
                ),
                (
                    "details",
                    models.JSONField(default=dict, help_text="Additional details about the action"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the actor", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string of the client"),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
                "db_table": "voyant_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "action", "-created_at"],
                        name="voyant_audi_tenant__d49377_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "resource_type", "resource_id"],
                        name="voyant_audi_tenant__3f6fd8_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="voyant_audi_actor_a87574_idx",
                    ),
                ],
            },
        ),
    ]
