# Generated by Django 5.2.17 on 2026-09-11 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable rule name",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of what this rule monitors",
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        help_text="Condition definition as JSON. Structure: {metric, operator, threshold, duration_seconds, labels}"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=16,
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text="List of notification channels: [{'type': 'email', 'target': 'ops@company.com'}, {'type': 'webhook', 'url': 'https://hooks.example.com/alert'}]",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this rule is actively evaluated",
                    ),
                ),
                (
                    "cooldown_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Minimum seconds between consecutive alerts for this rule",
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional labels for filtering and grouping",
                    ),
                ),
                (
                    "last_evaluated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this rule was last evaluated",
                        null=True,
                    ),
                ),
                (
                    "last_fired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this rule last fired an alert",
                        null=True,
                    ),
                ),
                (
                    "fire_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of times this rule has fired"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User or service that created this rule",
                        max_length=256,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Rule",
                "verbose_name_plural": "Alert Rules",
                "db_table": "voyant_alert_rule",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "-updated_at"],
                        name="voyant_aler_tenant__0d4408_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "enabled", "severity"],
                        name="voyant_aler_tenant__949130_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "-last_fired_at"],
                        name="voyant_aler_tenant__4faa3c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertNotification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        help_text="Severity of the alert",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(help_text="Human-readable alert message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("firing", "Firing"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("silenced", "Silenced"),
                        ],
                        db_index=True,
                        default="firing",
                        max_length=16,
                    ),
                ),
                (
                    "metric_value",
                    models.FloatField(
                        blank=True,
                        help_text="The metric value that triggered the alert",
                        null=True,
                    ),
                ),
                (
                    "threshold",
                    models.FloatField(
                        blank=True,
                        help_text="The threshold that was breached",
                        null=True,
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Labels from the rule and metric at time of firing",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (metric name, duration, etc.)",
                    ),
                ),
                (
                    "acknowledged_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User who acknowledged this alert",
                        max_length=256,
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this alert was acknowledged",
                        null=True,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When this alert was resolved", null=True
                    ),
                ),
                (
                    "channel_results",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Results of notification delivery per channel",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        help_text="The rule that generated this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.alertrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Notification",
                "verbose_name_plural": "Alert Notifications",
                "db_table": "voyant_alert_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "-created_at"],
                        name="voyant_aler_tenant__978076_idx",
                    ),
                    models.Index(
                        fields=["rule", "-created_at"],
                        name="voyant_aler_rule_id_89ffc6_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "severity", "-created_at"],
                        name="voyant_aler_tenant__51ff31_idx",
                    ),
                ],
            },
        ),
    ]
