# Generated by Django 5.2.17 on 2026-09-11 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UPTPTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique template name (e.g. 'ingest.db.generic')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of what this template does",
                    ),
                ),
                (
                    "template_body",
                    models.JSONField(
                        default=dict,
                        help_text="Template definition as JSON. Contains the DAG of steps, parameter declarations, input/output schemas, and execution hints.",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Monotonically increasing version number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Template lifecycle status",
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="Execution category (ingestion, math, render, capsule)",
                        max_length=64,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization and search",
                    ),
                ),
                (
                    "parameters_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema defining the expected parameters for this template. Used for runtime validation of instance parameters.",
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema describing the expected output format",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System templates cannot be deleted by users",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User or service that created this template",
                        max_length=256,
                    ),
                ),
            ],
            options={
                "verbose_name": "UPTP Template",
                "verbose_name_plural": "UPTP Templates",
                "db_table": "voyant_uptp_template",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "name"],
                        name="voyant_uptp_tenant__fcd929_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "category", "-updated_at"],
                        name="voyant_uptp_tenant__9c7b0c_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "status", "-created_at"],
                        name="voyant_uptp_tenant__7684d5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "name"),
                        name="uq_uptp_template_tenant_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UPTPInstance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Parameter values used for this execution",
                    ),
                ),
                (
                    "rendered_body",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The fully rendered template body (after parameter substitution)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validating", "Validating"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text="Execution result data (null while running)",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if the execution failed",
                    ),
                ),
                (
                    "workflow_instance_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Temporal workflow instance ID for async executions",
                        max_length=255,
                    ),
                ),
                (
                    "execution_urn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="UPTP execution URN (e.g. urn:voyant:job:tenant:template:uuid)",
                        max_length=512,
                    ),
                ),
                (
                    "execution_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The execution category at time of creation",
                        max_length=64,
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Execution duration in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When execution started", null=True
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, help_text="When execution finished", null=True
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        blank=True,
                        default="api",
                        help_text="What triggered this instance (api, scheduler, event, agent)",
                        max_length=128,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (session ID, agent context, etc.)",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The template this instance was created from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="uptp_core.uptptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "UPTP Instance",
                "verbose_name_plural": "UPTP Instances",
                "db_table": "voyant_uptp_instance",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "-created_at"],
                        name="voyant_uptp_tenant__edfe6f_idx",
                    ),
                    models.Index(
                        fields=["template", "-created_at"],
                        name="voyant_uptp_templat_55b856_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "execution_category", "-created_at"],
                        name="voyant_uptp_tenant__2dd93e_idx",
                    ),
                    models.Index(
                        fields=["workflow_instance_id"],
                        name="voyant_uptp_workflo_dd475d_idx",
                    ),
                    models.Index(
                        fields=["execution_urn"], name="voyant_uptp_executi_f9f587_idx"
                    ),
                ],
            },
        ),
    ]
