"""Scraper v4.0 — 51 pre-built templates for popular websites."""

TEMPLATES = [
    # ── E-Commerce (10) ──────────────────────────────────────────────────
    {
        "name": "Amazon Product Search",
        "category": "ecommerce",
        "site_pattern": "amazon.com",
        "description": "Search Amazon products by keyword",
        "engine": "playwright",
        "selectors": {
            "title": "h2 a span",
            "price": ".a-price .a-offscreen",
            "rating": ".a-icon-alt",
            "url": "h2 a[href]",
            "image": ".s-image",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.amazon.com/s?k={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "price", "rating", "url", "image"],
    },
    {
        "name": "Amazon Product Details",
        "category": "ecommerce",
        "site_pattern": "amazon.com",
        "description": "Extract detailed product info from Amazon product page",
        "engine": "playwright",
        "selectors": {
            "title": "#productTitle",
            "price": ".a-price .a-offscreen",
            "rating": "#acrPopover .a-icon-alt",
            "description": "#feature-bullets .a-list-item",
            "images": "#altImages img",
            "reviews_count": "#acrCustomerReviewText",
        },
        "workflow": [
            {"action": "navigate", "url": "{{product_url}}"},
            {"action": "extract"},
        ],
        "parameters": [{"name": "product_url", "type": "string", "required": True}],
        "output_fields": [
            "title",
            "price",
            "rating",
            "description",
            "images",
            "reviews_count",
        ],
    },
    {
        "name": "Amazon Product Reviews",
        "category": "ecommerce",
        "site_pattern": "amazon.com",
        "description": "Extract product reviews from Amazon",
        "engine": "playwright",
        "selectors": {
            "reviewer": ".a-profile-name",
            "rating": ".review-rating .a-icon-alt",
            "title": ".review-title span",
            "body": ".review-text span",
            "date": ".review-date",
        },
        "workflow": [
            {"action": "navigate", "url": "{{product_url}}"},
            {"action": "click", "selector": "[data-hook='see-all-reviews-link-foot']"},
            {"action": "scroll", "times": 5},
            {"action": "extract"},
        ],
        "parameters": [{"name": "product_url", "type": "string", "required": True}],
        "output_fields": ["reviewer", "rating", "title", "body", "date"],
    },
    {
        "name": "eBay Product Search",
        "category": "ecommerce",
        "site_pattern": "ebay.com",
        "description": "Search eBay products by keyword",
        "engine": "playwright",
        "selectors": {
            "title": ".s-item__title",
            "price": ".s-item__price",
            "url": ".s-item__link[href]",
            "image": ".s-item__image-img[src]",
            "condition": ".SECONDARY_INFO",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.ebay.com/sch/i.html?_nkw={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "price", "url", "image", "condition"],
    },
    {
        "name": "Walmart Product Listings",
        "category": "ecommerce",
        "site_pattern": "walmart.com",
        "description": "Search Walmart products",
        "engine": "playwright",
        "selectors": {
            "title": "[data-automation-id='product-title']",
            "price": "[data-automation-id='product-price'] .visuallyhidden",
            "url": "[data-automation-id='product-title'][href]",
            "rating": ".w_iUH7",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.walmart.com/search?q={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "price", "url", "rating"],
    },
    {
        "name": "Alibaba Product Search",
        "category": "ecommerce",
        "site_pattern": "alibaba.com",
        "description": "Search Alibaba products",
        "engine": "playwright",
        "selectors": {
            "title": ".organic-list .item-title-text",
            "price": ".organic-list .item-price",
            "url": ".organic-list .item-title a[href]",
            "min_order": ".min-order-limit",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.alibaba.com/trade/search?SearchText={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "price", "url", "min_order"],
    },
    {
        "name": "AliExpress Product Search",
        "category": "ecommerce",
        "site_pattern": "aliexpress.com",
        "description": "Search AliExpress products",
        "engine": "playwright",
        "selectors": {
            "title": ".item-title-text",
            "price": ".item-price",
            "url": ".item-title a[href]",
            "orders": ".item-trade",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.aliexpress.com/wholesale?SearchText={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "price", "url", "orders"],
    },
    {
        "name": "Shopify Store Products",
        "category": "ecommerce",
        "site_pattern": "*.myshopify.com",
        "description": "Extract products from any Shopify store",
        "engine": "playwright",
        "selectors": {
            "title": ".product-card .product-card__title",
            "price": ".product-card .price",
            "url": ".product-card a[href]",
            "image": ".product-card img[src]",
        },
        "workflow": [
            {"action": "navigate", "url": "{{store_url}}/collections/all"},
            {"action": "scroll", "times": 5},
            {"action": "extract"},
        ],
        "parameters": [{"name": "store_url", "type": "string", "required": True}],
        "output_fields": ["title", "price", "url", "image"],
    },
    {
        "name": "Etsy Product Search",
        "category": "ecommerce",
        "site_pattern": "etsy.com",
        "description": "Search Etsy products",
        "engine": "playwright",
        "selectors": {
            "title": ".v2-listing-card__info h3",
            "price": ".currency-value",
            "url": ".listing-link[href]",
            "shop": ".v2-listing-card__shop",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.etsy.com/search?q={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "price", "url", "shop"],
    },
    {
        "name": "Best Buy Product Search",
        "category": "ecommerce",
        "site_pattern": "bestbuy.com",
        "description": "Search Best Buy products",
        "engine": "playwright",
        "selectors": {
            "title": ".sku-title a",
            "price": ".priceView-customer-price span",
            "url": ".sku-title a[href]",
            "rating": ".c-stars-v4",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.bestbuy.com/site/searchpage.jsp?st={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "price", "url", "rating"],
    },
    # ── Maps (3) ─────────────────────────────────────────────────────────
    {
        "name": "Google Maps Business Listings",
        "category": "maps",
        "site_pattern": "google.com/maps",
        "description": "Extract business listings from Google Maps",
        "engine": "playwright",
        "selectors": {
            "name": ".qBF1Pd",
            "rating": ".MW4etd",
            "reviews": ".UY7F9",
            "address": ".rllt__details div:nth-child(3)",
            "phone": ".rllt__details div:nth-child(4)",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.google.com/maps/search/{{search_query}}",
            },
            {"action": "wait", "selector": ".qBF1Pd"},
            {"action": "scroll", "times": 5},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["name", "rating", "reviews", "address", "phone"],
    },
    {
        "name": "Google Maps Business Reviews",
        "category": "maps",
        "site_pattern": "google.com/maps",
        "description": "Extract reviews for a specific business",
        "engine": "playwright",
        "selectors": {
            "reviewer": ".d4r55",
            "rating": ".kvMYJc",
            "text": ".wiI7pd",
            "date": ".rsqaWe",
        },
        "workflow": [
            {"action": "navigate", "url": "{{business_url}}"},
            {"action": "click", "selector": "button[data-tab-id='reviews']"},
            {"action": "scroll", "times": 10},
            {"action": "extract"},
        ],
        "parameters": [{"name": "business_url", "type": "string", "required": True}],
        "output_fields": ["reviewer", "rating", "text", "date"],
    },
    {
        "name": "Google Maps Business Details",
        "category": "maps",
        "site_pattern": "google.com/maps",
        "description": "Extract detailed business info",
        "engine": "playwright",
        "selectors": {
            "name": "h1",
            "address": "[data-item-id='address']",
            "phone": "[data-item-id*='phone']",
            "website": "[data-item-id='authority']",
            "hours": "[aria-label*='hours']",
            "rating": ".fontDisplayLarge",
        },
        "workflow": [
            {"action": "navigate", "url": "{{business_url}}"},
            {"action": "wait", "selector": "h1"},
            {"action": "extract"},
        ],
        "parameters": [{"name": "business_url", "type": "string", "required": True}],
        "output_fields": ["name", "address", "phone", "website", "hours", "rating"],
    },
    # ── Social Media (8) ─────────────────────────────────────────────────
    {
        "name": "Twitter/X Post Search",
        "category": "social",
        "site_pattern": "x.com",
        "description": "Search Twitter/X posts by keyword",
        "engine": "playwright",
        "selectors": {
            "text": "[data-testid='tweetText']",
            "author": "[data-testid='User-Name']",
            "likes": "[data-testid='like'] span",
            "retweets": "[data-testid='retweet'] span",
            "date": "time",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://x.com/search?q={{search_query}}&src=typed_query",
            },
            {"action": "scroll", "times": 5},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["text", "author", "likes", "retweets", "date"],
    },
    {
        "name": "Twitter/X User Profile",
        "category": "social",
        "site_pattern": "x.com",
        "description": "Extract user profile and recent tweets",
        "engine": "playwright",
        "selectors": {
            "display_name": "[data-testid='UserName']",
            "bio": "[data-testid='UserDescription']",
            "followers": "a[href*='followers'] span",
            "following": "a[href*='following'] span",
        },
        "workflow": [
            {"action": "navigate", "url": "https://x.com/{{username}}"},
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "username", "type": "string", "required": True}],
        "output_fields": ["display_name", "bio", "followers", "following"],
    },
    {
        "name": "YouTube Video Search",
        "category": "social",
        "site_pattern": "youtube.com",
        "description": "Search YouTube videos",
        "engine": "playwright",
        "selectors": {
            "title": "#video-title",
            "channel": "#channel-name a",
            "views": "#metadata-line span:first-child",
            "date": "#metadata-line span:nth-child(2)",
            "url": "#video-title[href]",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.youtube.com/results?search_query={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "channel", "views", "date", "url"],
    },
    {
        "name": "YouTube Video Details",
        "category": "social",
        "site_pattern": "youtube.com",
        "description": "Extract video details and comments",
        "engine": "playwright",
        "selectors": {
            "title": "h1 yt-formatted-string",
            "views": "#info-container span:first-child",
            "likes": "#top-level-buttons-computed button:first-child",
            "description": "#description-inner",
            "channel": "#channel-name a",
        },
        "workflow": [
            {"action": "navigate", "url": "{{video_url}}"},
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "video_url", "type": "string", "required": True}],
        "output_fields": ["title", "views", "likes", "description", "channel"],
    },
    {
        "name": "Reddit Post Search",
        "category": "social",
        "site_pattern": "reddit.com",
        "description": "Search Reddit posts",
        "engine": "playwright",
        "selectors": {
            "title": "h3",
            "author": ".author-name",
            "score": "[score]",
            "comments": ".comment-count",
            "url": "a[data-click-id='body']",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.reddit.com/search/?q={{search_query}}",
            },
            {"action": "scroll", "times": 5},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "author", "score", "comments", "url"],
    },
    {
        "name": "Reddit Subreddit Posts",
        "category": "social",
        "site_pattern": "reddit.com",
        "description": "Extract posts from a subreddit",
        "engine": "playwright",
        "selectors": {
            "title": "h3",
            "author": ".author-name",
            "score": "[score]",
            "url": "a[data-click-id='body']",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.reddit.com/r/{{subreddit}}/hot/",
            },
            {"action": "scroll", "times": 5},
            {"action": "extract"},
        ],
        "parameters": [{"name": "subreddit", "type": "string", "required": True}],
        "output_fields": ["title", "author", "score", "url"],
    },
    {
        "name": "LinkedIn Profile",
        "category": "social",
        "site_pattern": "linkedin.com",
        "description": "Extract LinkedIn profile data",
        "engine": "playwright",
        "selectors": {
            "name": ".text-heading-xlarge",
            "headline": ".text-body-medium",
            "location": ".text-body-small.inline",
            "about": ".inline-show-more-text",
            "experience": ".experience-section",
        },
        "workflow": [
            {"action": "navigate", "url": "{{profile_url}}"},
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "profile_url", "type": "string", "required": True}],
        "output_fields": ["name", "headline", "location", "about", "experience"],
    },
    {
        "name": "LinkedIn Company Data",
        "category": "social",
        "site_pattern": "linkedin.com",
        "description": "Extract company page data",
        "engine": "playwright",
        "selectors": {
            "name": ".org-top-card-summary__title",
            "industry": ".org-top-card-summary__industry",
            "size": ".org-top-card-summary__info-item",
            "about": ".org-about-us-organization-description",
        },
        "workflow": [
            {"action": "navigate", "url": "{{company_url}}"},
            {"action": "scroll", "times": 2},
            {"action": "extract"},
        ],
        "parameters": [{"name": "company_url", "type": "string", "required": True}],
        "output_fields": ["name", "industry", "size", "about"],
    },
    # ── Lead Generation (3) ──────────────────────────────────────────────
    {
        "name": "Email Extraction",
        "category": "leadgen",
        "site_pattern": "*",
        "description": "Extract emails from any webpage",
        "engine": "httpx",
        "selectors": {},
        "workflow": [
            {"action": "fetch", "url": "{{target_url}}"},
            {"action": "extract_emails"},
        ],
        "parameters": [{"name": "target_url", "type": "string", "required": True}],
        "output_fields": ["emails"],
    },
    {
        "name": "Yellow Pages Contact Info",
        "category": "leadgen",
        "site_pattern": "yellowpages.com",
        "description": "Extract business contact info from Yellow Pages",
        "engine": "playwright",
        "selectors": {
            "name": ".business-name",
            "phone": ".phones",
            "address": ".street-address",
            "website": ".website a[href]",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.yellowpages.com/search?search_terms={{search_query}}&geo_location_terms={{location}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [
            {"name": "search_query", "type": "string", "required": True},
            {"name": "location", "type": "string", "required": True},
        ],
        "output_fields": ["name", "phone", "address", "website"],
    },
    {
        "name": "Yelp Business Directory",
        "category": "leadgen",
        "site_pattern": "yelp.com",
        "description": "Extract business listings from Yelp",
        "engine": "playwright",
        "selectors": {
            "name": ".businessName__09f24__EYSZE",
            "rating": ".aria-label_1qg8S",
            "reviews": ".reviewCount__09f24__EUXdS",
            "address": ".address__09f24__XG1SK",
            "price": ".priceRange__09f24__pNRiI",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.yelp.com/search?find_desc={{search_query}}&find_loc={{location}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [
            {"name": "search_query", "type": "string", "required": True},
            {"name": "location", "type": "string", "required": True},
        ],
        "output_fields": ["name", "rating", "reviews", "address", "price"],
    },
    # ── Jobs (3) ─────────────────────────────────────────────────────────
    {
        "name": "Indeed Job Search",
        "category": "jobs",
        "site_pattern": "indeed.com",
        "description": "Search jobs on Indeed",
        "engine": "playwright",
        "selectors": {
            "title": ".jobTitle",
            "company": ".companyName",
            "location": ".companyLocation",
            "salary": ".salary-snippet",
            "summary": ".job-snippet",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.indeed.com/jobs?q={{search_query}}&l={{location}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [
            {"name": "search_query", "type": "string", "required": True},
            {"name": "location", "type": "string", "required": False},
        ],
        "output_fields": ["title", "company", "location", "salary", "summary"],
    },
    {
        "name": "Indeed Job Details",
        "category": "jobs",
        "site_pattern": "indeed.com",
        "description": "Extract detailed job info from Indeed",
        "engine": "playwright",
        "selectors": {
            "title": ".jobsearch-JobInfoHeader-title",
            "company": ".css-1cxcq8a",
            "location": ".css-1b4ef20",
            "description": "#jobDescriptionText",
            "salary": ".css-1b4ef20",
        },
        "workflow": [
            {"action": "navigate", "url": "{{job_url}}"},
            {"action": "extract"},
        ],
        "parameters": [{"name": "job_url", "type": "string", "required": True}],
        "output_fields": ["title", "company", "location", "description", "salary"],
    },
    {
        "name": "LinkedIn Job Search",
        "category": "jobs",
        "site_pattern": "linkedin.com",
        "description": "Search LinkedIn jobs",
        "engine": "playwright",
        "selectors": {
            "title": ".job-card-list__title",
            "company": ".job-card-container__primary-description",
            "location": ".job-card-container__metadata-item",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.linkedin.com/jobs/search/?keywords={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "company", "location"],
    },
    # ── Real Estate (3) ──────────────────────────────────────────────────
    {
        "name": "Zillow Property Listings",
        "category": "realestate",
        "site_pattern": "zillow.com",
        "description": "Search Zillow property listings",
        "engine": "playwright",
        "selectors": {
            "address": ".property-card-data address",
            "price": ".PropertyCardWrapper span[data-test='property-card-price']",
            "beds": ".beds",
            "baths": ".baths",
            "sqft": ".sqft",
            "url": ".property-card-link[href]",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.zillow.com/homes/{{location}}_rb/",
            },
            {"action": "scroll", "times": 5},
            {"action": "extract"},
        ],
        "parameters": [{"name": "location", "type": "string", "required": True}],
        "output_fields": ["address", "price", "beds", "baths", "sqft", "url"],
    },
    {
        "name": "Zillow Property Details",
        "category": "realestate",
        "site_pattern": "zillow.com",
        "description": "Extract detailed property info from Zillow",
        "engine": "playwright",
        "selectors": {
            "price": ".ds-price .ds-value",
            "beds": "[data-testid='bed-bath-item']:nth-child(1)",
            "baths": "[data-testid='bed-bath-item']:nth-child(2)",
            "sqft": "[data-testid='bed-bath-item']:nth-child(3)",
            "year_built": ".ds-home-fact-list-item",
            "zestimate": ".zestimate",
        },
        "workflow": [
            {"action": "navigate", "url": "{{property_url}}"},
            {"action": "extract"},
        ],
        "parameters": [{"name": "property_url", "type": "string", "required": True}],
        "output_fields": ["price", "beds", "baths", "sqft", "year_built", "zestimate"],
    },
    {
        "name": "Realtor.com Property Listings",
        "category": "realestate",
        "site_pattern": "realtor.com",
        "description": "Search Realtor.com listings",
        "engine": "playwright",
        "selectors": {
            "address": ".card-address",
            "price": ".card-price",
            "beds": ".property-beds",
            "baths": ".property-baths",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.realtor.com/realestateandhomes-search/{{location}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "location", "type": "string", "required": True}],
        "output_fields": ["address", "price", "beds", "baths"],
    },
    # ── News (3) ─────────────────────────────────────────────────────────
    {
        "name": "Google News Article Search",
        "category": "news",
        "site_pattern": "news.google.com",
        "description": "Search Google News articles",
        "engine": "playwright",
        "selectors": {
            "title": "article h3",
            "source": "article .vr1PYe",
            "time": "article time",
            "url": "article a[href]",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://news.google.com/search?q={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "source", "time", "url"],
    },
    {
        "name": "Any News Site Article Content",
        "category": "news",
        "site_pattern": "*",
        "description": "Extract article content from any news site",
        "engine": "playwright",
        "selectors": {
            "title": "h1",
            "author": ".author, [rel='author']",
            "date": "time, .date, .published",
            "content": "article p, .article-body p",
        },
        "workflow": [
            {"action": "navigate", "url": "{{article_url}}"},
            {"action": "extract"},
        ],
        "parameters": [{"name": "article_url", "type": "string", "required": True}],
        "output_fields": ["title", "author", "date", "content"],
    },
    {
        "name": "Hacker News",
        "category": "news",
        "site_pattern": "news.ycombinator.com",
        "description": "Extract Hacker News front page",
        "engine": "httpx",
        "selectors": {
            "title": ".titleline a",
            "url": ".titleline a[href]",
            "score": ".score",
            "comments": ".subtext a:last-child",
        },
        "workflow": [
            {"action": "fetch", "url": "https://news.ycombinator.com/"},
            {"action": "extract"},
        ],
        "parameters": [],
        "output_fields": ["title", "url", "score", "comments"],
    },
    # ── Finance (2) ──────────────────────────────────────────────────────
    {
        "name": "Yahoo Finance Stock Data",
        "category": "finance",
        "site_pattern": "finance.yahoo.com",
        "description": "Extract stock data from Yahoo Finance",
        "engine": "playwright",
        "selectors": {
            "price": "[data-field='regularMarketPrice']",
            "change": "[data-field='regularMarketChange']",
            "volume": "[data-field='regularMarketVolume']",
            "market_cap": "[data-field='marketCap']",
        },
        "workflow": [
            {"action": "navigate", "url": "https://finance.yahoo.com/quote/{{ticker}}"},
            {"action": "extract"},
        ],
        "parameters": [{"name": "ticker", "type": "string", "required": True}],
        "output_fields": ["price", "change", "volume", "market_cap"],
    },
    {
        "name": "Crunchbase Company Data",
        "category": "finance",
        "site_pattern": "crunchbase.com",
        "description": "Extract company data from Crunchbase",
        "engine": "playwright",
        "selectors": {
            "name": ".profile-name",
            "description": ".description",
            "funding": ".funding-total",
            "employees": ".company-employees",
            "industry": ".industry-list",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.crunchbase.com/organization/{{company_slug}}",
            },
            {"action": "extract"},
        ],
        "parameters": [{"name": "company_slug", "type": "string", "required": True}],
        "output_fields": ["name", "description", "funding", "employees", "industry"],
    },
    # ── Travel (3) ───────────────────────────────────────────────────────
    {
        "name": "Booking.com Hotel Search",
        "category": "travel",
        "site_pattern": "booking.com",
        "description": "Search hotels on Booking.com",
        "engine": "playwright",
        "selectors": {
            "name": "[data-testid='title']",
            "price": "[data-testid='price-and-discounted-price']",
            "rating": "[data-testid='review-score']",
            "address": "[data-testid='address']",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.booking.com/searchresults.html?ss={{destination}}&checkin={{checkin}}&checkout={{checkout}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [
            {"name": "destination", "type": "string", "required": True},
            {"name": "checkin", "type": "string", "required": True},
            {"name": "checkout", "type": "string", "required": True},
        ],
        "output_fields": ["name", "price", "rating", "address"],
    },
    {
        "name": "Google Flights Search",
        "category": "travel",
        "site_pattern": "google.com/travel/flights",
        "description": "Search flights on Google Flights",
        "engine": "playwright",
        "selectors": {
            "airline": ".airline-name",
            "departure": ".departure-time",
            "arrival": ".arrival-time",
            "duration": ".duration",
            "price": ".price",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.google.com/travel/flights/search?tfs=CBwQAhoeagwIAhIIL20vMGpmcnoSCggCEgYvbS8wN20yGgJAAUABSAFwAYIBCwj___________8BQAFIAZgBAQ&hl=en&gl=us&curr=USD",
            },
            {"action": "extract"},
        ],
        "parameters": [],
        "output_fields": ["airline", "departure", "arrival", "duration", "price"],
    },
    {
        "name": "TripAdvisor Restaurant Reviews",
        "category": "travel",
        "site_pattern": "tripadvisor.com",
        "description": "Extract restaurant reviews from TripAdvisor",
        "engine": "playwright",
        "selectors": {
            "reviewer": ".info_text div",
            "rating": ".ui_bubble_rating",
            "title": ".noQuotes",
            "text": ".partial_entry",
            "date": ".ratingDate",
        },
        "workflow": [
            {"action": "navigate", "url": "{{restaurant_url}}"},
            {"action": "scroll", "times": 5},
            {"action": "extract"},
        ],
        "parameters": [{"name": "restaurant_url", "type": "string", "required": True}],
        "output_fields": ["reviewer", "rating", "title", "text", "date"],
    },
    # ── Education (2) ────────────────────────────────────────────────────
    {
        "name": "Coursera Course Search",
        "category": "education",
        "site_pattern": "coursera.org",
        "description": "Search Coursera courses",
        "engine": "playwright",
        "selectors": {
            "title": ".card-title",
            "partner": ".partner",
            "rating": ".ratings",
            "skills": ".skills",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.coursera.org/search?query={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "partner", "rating", "skills"],
    },
    {
        "name": "Google Scholar Research Papers",
        "category": "education",
        "site_pattern": "scholar.google.com",
        "description": "Search academic papers on Google Scholar",
        "engine": "playwright",
        "selectors": {
            "title": ".gs_rt a",
            "authors": ".gs_a",
            "abstract": ".gs_rs",
            "citations": ".gs_fl a:first-child",
            "url": ".gs_rt a[href]",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://scholar.google.com/scholar?q={{search_query}}",
            },
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "authors", "abstract", "citations", "url"],
    },
    # ── Developer (3) ────────────────────────────────────────────────────
    {
        "name": "GitHub Repository Search",
        "category": "developer",
        "site_pattern": "github.com",
        "description": "Search GitHub repositories",
        "engine": "httpx",
        "selectors": {},
        "workflow": [
            {
                "action": "api",
                "url": "https://api.github.com/search/repositories?q={{search_query}}&sort=stars",
            },
            {
                "action": "extract_json",
                "fields": [
                    "items[].full_name",
                    "items[].description",
                    "items[].stargazers_count",
                    "items[].language",
                ],
            },
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["name", "description", "stars", "language"],
    },
    {
        "name": "npm Package Search",
        "category": "developer",
        "site_pattern": "npmjs.com",
        "description": "Search npm packages",
        "engine": "httpx",
        "selectors": {},
        "workflow": [
            {
                "action": "api",
                "url": "https://registry.npmjs.org/-/v1/search?text={{search_query}}&size=20",
            },
            {
                "action": "extract_json",
                "fields": [
                    "objects[].package.name",
                    "objects[].package.description",
                    "objects[].package.version",
                ],
            },
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["name", "description", "version"],
    },
    {
        "name": "Stack Overflow Questions",
        "category": "developer",
        "site_pattern": "stackoverflow.com",
        "description": "Search Stack Overflow questions",
        "engine": "httpx",
        "selectors": {},
        "workflow": [
            {
                "action": "api",
                "url": "https://api.stackexchange.com/2.3/search?order=desc&sort=activity&intitle={{search_query}}&site=stackoverflow",
            },
            {
                "action": "extract_json",
                "fields": [
                    "items[].title",
                    "items[].link",
                    "items[].score",
                    "items[].answer_count",
                ],
            },
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "url", "score", "answers"],
    },
    # ── Search Engines (2) ───────────────────────────────────────────────
    {
        "name": "Google Search Results",
        "category": "search",
        "site_pattern": "google.com",
        "description": "Extract Google search results",
        "engine": "playwright",
        "selectors": {
            "title": "h3",
            "url": "a[href]",
            "snippet": ".VwiC3b",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.google.com/search?q={{search_query}}",
            },
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "url", "snippet"],
    },
    {
        "name": "Bing Search Results",
        "category": "search",
        "site_pattern": "bing.com",
        "description": "Extract Bing search results",
        "engine": "playwright",
        "selectors": {
            "title": "h2 a",
            "url": "h2 a[href]",
            "snippet": ".b_caption p",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.bing.com/search?q={{search_query}}",
            },
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["title", "url", "snippet"],
    },
    # ── Directory (2) ────────────────────────────────────────────────────
    {
        "name": "Yellow Pages Business Directory",
        "category": "directory",
        "site_pattern": "yellowpages.com",
        "description": "Extract business listings from Yellow Pages",
        "engine": "playwright",
        "selectors": {
            "name": ".business-name",
            "phone": ".phones",
            "address": ".street-address",
            "categories": ".categories",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.yellowpages.com/search?search_terms={{search_query}}&geo_location_terms={{location}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [
            {"name": "search_query", "type": "string", "required": True},
            {"name": "location", "type": "string", "required": True},
        ],
        "output_fields": ["name", "phone", "address", "categories"],
    },
    {
        "name": "Clutch.co Professional Directory",
        "category": "directory",
        "site_pattern": "clutch.co",
        "description": "Extract company listings from Clutch",
        "engine": "playwright",
        "selectors": {
            "name": ".company-name",
            "rating": ".rating",
            "reviews": ".reviews-count",
            "services": ".services-list",
            "location": ".location",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://clutch.co/search?query={{search_query}}",
            },
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["name", "rating", "reviews", "services", "location"],
    },
    # ── Social (additional) ──────────────────────────────────────────────
    {
        "name": "TikTok Video Search",
        "category": "social",
        "site_pattern": "tiktok.com",
        "description": "Search TikTok videos",
        "engine": "playwright",
        "selectors": {
            "description": "[data-e2e='search-card-desc']",
            "author": "[data-e2e='search-card-user-link']",
            "likes": "[data-e2e='search-card-like-count']",
            "url": "a[href*='/video/']",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.tiktok.com/search?q={{search_query}}",
            },
            {"action": "scroll", "times": 5},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["description", "author", "likes", "url"],
    },
    {
        "name": "Instagram Post Search",
        "category": "social",
        "site_pattern": "instagram.com",
        "description": "Search Instagram posts by hashtag",
        "engine": "playwright",
        "selectors": {
            "image": "article img[src]",
            "likes": "section span",
            "comments": "section span:nth-child(2)",
            "url": "a[href*='/p/']",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.instagram.com/explore/tags/{{hashtag}}",
            },
            {"action": "scroll", "times": 5},
            {"action": "extract"},
        ],
        "parameters": [{"name": "hashtag", "type": "string", "required": True}],
        "output_fields": ["image", "likes", "comments", "url"],
    },
    {
        "name": "Facebook Post Search",
        "category": "social",
        "site_pattern": "facebook.com",
        "description": "Search Facebook posts",
        "engine": "playwright",
        "selectors": {
            "text": "[data-ad-preview='message']",
            "author": ".nc684nl6 a",
            "url": "a[href*='/posts/']",
        },
        "workflow": [
            {
                "action": "navigate",
                "url": "https://www.facebook.com/search/posts/?q={{search_query}}",
            },
            {"action": "scroll", "times": 5},
            {"action": "extract"},
        ],
        "parameters": [{"name": "search_query", "type": "string", "required": True}],
        "output_fields": ["text", "author", "url"],
    },
    # ── Universal ────────────────────────────────────────────────────────
    {
        "name": "Any Page to Markdown",
        "category": "universal",
        "site_pattern": "*",
        "description": "Convert any webpage to clean Markdown text",
        "engine": "httpx",
        "selectors": {},
        "workflow": [
            {"action": "fetch", "url": "{{target_url}}"},
            {"action": "extract_markdown"},
        ],
        "parameters": [{"name": "target_url", "type": "string", "required": True}],
        "output_fields": ["markdown", "title", "url"],
    },
    # ── Additional (1) ───────────────────────────────────────────────────────
    {
        "name": "X/Twitter Trending Topics",
        "category": "social",
        "site_pattern": "x.com",
        "description": "Extract trending topics and hashtags from X/Twitter Explore",
        "engine": "playwright",
        "selectors": {
            "trend_name": "[data-testid='trend']",
            "tweet_count": "[data-testid='trend'] + div",
            "category": "[data-testid='trend-category']",
        },
        "workflow": [
            {"action": "navigate", "url": "https://x.com/explore/tabs/trending"},
            {"action": "scroll", "times": 3},
            {"action": "extract"},
        ],
        "parameters": [],
        "output_fields": ["trend_name", "tweet_count", "category"],
    },
]
