# Generated by Django 6.0.2 on 2026-09-09 12:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Dashboard name (unique per tenant)", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Human-readable description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Publication status",
                        max_length=20,
                    ),
                ),
                (
                    "layout",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Dashboard layout configuration: {"columns": 12, "row_height": 80, "gap": 8, "responsive": true}',
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Tags for categorization: ["monitoring", "sales"]',
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this dashboard is visible to all tenant users",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="User who created the dashboard",
                        max_length=256,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Soft-deletion timestamp (null = active)",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "voyant_dashboard",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="idx_dash_tenant_status"
                    ),
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="idx_dash_tenant_created",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant_id", "name"),
                        name="uq_dashboard_name_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("chart_bar", "Bar Chart"),
                            ("chart_line", "Line Chart"),
                            ("chart_pie", "Pie Chart"),
                            ("chart_area", "Area Chart"),
                            ("chart_scatter", "Scatter Plot"),
                            ("table", "Data Table"),
                            ("metric", "Single Metric"),
                            ("kpi", "KPI Card"),
                            ("text", "Text / Markdown"),
                            ("iframe", "Embedded IFrame"),
                            ("map", "Map"),
                            ("heatmap", "Heatmap"),
                            ("custom", "Custom"),
                        ],
                        help_text="Type of visual element",
                        max_length=32,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Widget title displayed in the header",
                        max_length=255,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Widget-specific configuration: {"data_source": "sql", "query": "SELECT ...", "color": "#4f46e5", "refresh_interval": 60, "options": {}}',
                    ),
                ),
                (
                    "position_x",
                    models.PositiveIntegerField(
                        default=0, help_text="Column position (0-based, 12-column grid)"
                    ),
                ),
                (
                    "position_y",
                    models.PositiveIntegerField(
                        default=0, help_text="Row position (0-based)"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        default=6, help_text="Number of columns spanned (1-12)"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        default=4, help_text="Number of rows spanned"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Z-index / render order"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True, help_text="Whether the widget is visible"
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        help_text="Parent dashboard",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="dashboard_builder.dashboard",
                    ),
                ),
            ],
            options={
                "db_table": "voyant_widget",
                "ordering": ["order", "position_y", "position_x"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["dashboard_id", "order"], name="idx_widget_dash_order"
                    )
                ],
            },
        ),
    ]
