# Generated by Django 6.0.2 on 2026-05-22 11:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("schema", models.JSONField(default=dict)),
                ("config", models.JSONField(default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "capabilities",
                "db_table": "capabilities",
            },
        ),
        migrations.CreateModel(
            name="Capsule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("certified", "Certified"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("system_prompt", models.TextField(default="")),
                ("personality_traits", models.JSONField(default=dict)),
                ("neuromodulator_baseline", models.JSONField(default=dict)),
                (
                    "capsule_type",
                    models.CharField(
                        db_index=True,
                        default="voyant.intelligence_recipe",
                        max_length=100,
                    ),
                ),
                ("execution_graph", models.JSONField(default=list)),
                ("parameters_schema", models.JSONField(default=dict)),
                ("output_formats", models.JSONField(default=list)),
                ("rbac_rules", models.JSONField(default=dict)),
                ("capabilities_whitelist", models.JSONField(default=list)),
                ("resource_limits", models.JSONField(default=dict)),
                ("constitution_ref", models.JSONField(blank=True, default=dict)),
                ("registry_signature", models.TextField(blank=True, null=True)),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("install_count", models.PositiveIntegerField(default=0)),
                ("execution_count", models.PositiveIntegerField(default=0)),
                (
                    "capabilities",
                    models.ManyToManyField(
                        blank=True, related_name="capsules", to="capsules.capability"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent capsule this was cloned from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="capsules.capsule",
                    ),
                ),
            ],
            options={
                "db_table": "capsules",
            },
        ),
        migrations.CreateModel(
            name="CapsuleInstallation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("installed_by", models.CharField(blank=True, max_length=255)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("parameter_overrides", models.JSONField(blank=True, default=dict)),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="capsules.capsule",
                    ),
                ),
            ],
            options={
                "db_table": "capsule_installations",
            },
        ),
        migrations.CreateModel(
            name="CapsuleInstance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "job_urn",
                    models.CharField(blank=True, db_index=True, max_length=512),
                ),
                ("state", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=50,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(db_index=True, default="mcp", max_length=50),
                ),
                ("parameter_values", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="capsules.capsule",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="capsules.capsuleinstallation",
                    ),
                ),
            ],
            options={
                "db_table": "capsule_instances",
            },
        ),
        migrations.CreateModel(
            name="Constitution",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                (
                    "content_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("signature", models.TextField()),
                ("content", models.JSONField()),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "constitutions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="constitutio_is_acti_3b6f83_idx"
                    ),
                    models.Index(
                        fields=["content_hash"], name="constitutio_content_431263_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="capsule",
            name="constitution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capsules",
                to="capsules.constitution",
            ),
        ),
        migrations.AddIndex(
            model_name="capsuleinstallation",
            index=models.Index(
                fields=["tenant_id", "is_enabled"],
                name="capsule_ins_tenant__582a0b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="capsuleinstallation",
            unique_together={("capsule", "tenant_id")},
        ),
        migrations.AddIndex(
            model_name="capsuleinstance",
            index=models.Index(
                fields=["tenant_id", "status"], name="capsule_ins_tenant__8c580e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capsuleinstance",
            index=models.Index(
                fields=["session_id", "status"], name="capsule_ins_session_134d6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capsuleinstance",
            index=models.Index(
                fields=["job_urn"], name="capsule_ins_job_urn_f8c787_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capsule",
            index=models.Index(
                fields=["tenant_id", "status"], name="capsules_tenant__fb8024_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capsule",
            index=models.Index(
                fields=["tenant_id", "name", "version"],
                name="capsules_tenant__585481_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="capsule",
            index=models.Index(
                fields=["capsule_type", "status"], name="capsules_capsule_8b20b0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="capsule",
            unique_together={("name", "version", "tenant_id")},
        ),
    ]
