# Generated by Django 5.2.17 on 2026-09-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalrequest",
            options={},
        ),
        migrations.AlterModelOptions(
            name="approvalrule",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="approvalrequest",
            name="approvalrequ_tenant__b0c1f8_idx",
        ),
        migrations.RemoveIndex(
            model_name="approvalrequest",
            name="approvalrequ_realm_0f2e77_idx",
        ),
        migrations.RemoveIndex(
            model_name="approvalrule",
            name="approvalrule_tenant__8a4e95_idx",
        ),
        migrations.RemoveIndex(
            model_name="approvalrule",
            name="approvalrule_realm_d3b1c0_idx",
        ),
    ]
