# Generated by Django 5.0.6 on 2026-05-22 09:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_instance_id",
                    models.CharField(
                        db_index=True,
                        help_text="Temporal workflow instance ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("partial", "Partial Success"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current job status",
                        max_length=16,
                    ),
                ),
                (
                    "progress",
                    models.FloatField(
                        default=0.0, help_text="Job progress (0.0 to 1.0)"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True, help_text="Current execution stage", max_length=64
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        default=dict, help_text="Job parameters and configuration"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Job result data", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if job failed"
                    ),
                ),
                (
                    "rows_ingested",
                    models.BigIntegerField(
                        default=0, help_text="Number of rows successfully ingested"
                    ),
                ),
                (
                    "bytes_processed",
                    models.BigIntegerField(
                        default=0, help_text="Number of bytes processed"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when job started execution",
                        null=True,
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when job finished", null=True
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Source to ingest data from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_jobs",
                        to="discovery.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingestion Job",
                "verbose_name_plural": "Ingestion Jobs",
                "db_table": "voyant_ingestion_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "-created_at"],
                        name="voyant_inge_tenant__41fca7_idx",
                    ),
                    models.Index(
                        fields=["source", "-created_at"],
                        name="voyant_inge_source__91296f_idx",
                    ),
                    models.Index(
                        fields=["workflow_instance_id"],
                        name="voyant_inge_workflo_fc7491_idx",
                    ),
                ],
            },
        ),
    ]
