# Generated by Django 5.0.6 on 2026-06-14 10:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CDCConnection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_instance_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Temporal workflow instance ID driving this CDC stream",
                        max_length=255,
                    ),
                ),
                (
                    "replication_slot",
                    models.CharField(
                        default="voyant_cdc_slot",
                        help_text="PostgreSQL logical replication slot name",
                        max_length=128,
                    ),
                ),
                (
                    "publication_name",
                    models.CharField(
                        default="voyant_cdc_pub",
                        help_text="PostgreSQL publication name",
                        max_length=128,
                    ),
                ),
                (
                    "tables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of table names to monitor (empty = all tables)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("starting", "Starting"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                            ("stopped", "Stopped"),
                        ],
                        db_index=True,
                        default="created",
                        help_text="Current CDC connection status",
                        max_length=16,
                    ),
                ),
                (
                    "last_lsn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Last acknowledged WAL Log Sequence Number (watermark)",
                        max_length=64,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last processed change event",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the CDC stream failed",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="CDC-specific configuration (connection string, batch size, etc.)",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Source this CDC connection monitors",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cdc_connections",
                        to="discovery.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "CDC Connection",
                "verbose_name_plural": "CDC Connections",
                "db_table": "voyant_cdc_connection",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "-created_at"],
                        name="voyant_cdc_tenant_s_idx",
                    ),
                    models.Index(
                        fields=["source", "status"],
                        name="voyant_cdc_source_s_idx",
                    ),
                    models.Index(
                        fields=["workflow_instance_id"],
                        name="voyant_cdc_workflo_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CDCChangeEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("INSERT", "Insert"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        db_index=True,
                        help_text="Type of change operation",
                        max_length=8,
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        db_index=True,
                        help_text="Source table that changed",
                        max_length=256,
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        default="public",
                        help_text="Source schema name",
                        max_length=128,
                    ),
                ),
                (
                    "primary_key",
                    models.JSONField(
                        blank=True,
                        help_text="Primary key value(s) of the affected row",
                        null=True,
                    ),
                ),
                (
                    "before_data",
                    models.JSONField(
                        blank=True,
                        help_text="Row data before the change (null for INSERTs)",
                        null=True,
                    ),
                ),
                (
                    "after_data",
                    models.JSONField(
                        blank=True,
                        help_text="Row data after the change (null for DELETEs)",
                        null=True,
                    ),
                ),
                (
                    "lsn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="WAL Log Sequence Number of this change",
                        max_length=64,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the change was captured (from the source)",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        help_text="CDC connection that captured this change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_events",
                        to="ingestion.cdcconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "CDC Change Event",
                "verbose_name_plural": "CDC Change Events",
                "db_table": "voyant_cdc_change_event",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["connection", "operation", "-timestamp"],
                        name="voyant_cdc_conn_op_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "table_name", "-timestamp"],
                        name="voyant_cdc_tenant_t_idx",
                    ),
                    models.Index(
                        fields=["connection", "lsn"],
                        name="voyant_cdc_conn_ls_idx",
                    ),
                ],
            },
        ),
    ]
