# Generated by Django 5.2.17 on 2026-09-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_cdcconnection_cdcchangeevent"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cdcchangeevent",
            new_name="voyant_cdc__connect_51c6ab_idx",
            old_name="voyant_cdc_conn_op_idx",
        ),
        migrations.RenameIndex(
            model_name="cdcchangeevent",
            new_name="voyant_cdc__tenant__a37cd7_idx",
            old_name="voyant_cdc_tenant_t_idx",
        ),
        migrations.RenameIndex(
            model_name="cdcchangeevent",
            new_name="voyant_cdc__connect_0ad398_idx",
            old_name="voyant_cdc_conn_ls_idx",
        ),
        migrations.RenameIndex(
            model_name="cdcconnection",
            new_name="voyant_cdc__tenant__960df4_idx",
            old_name="voyant_cdc_tenant_s_idx",
        ),
        migrations.RenameIndex(
            model_name="cdcconnection",
            new_name="voyant_cdc__source__747001_idx",
            old_name="voyant_cdc_source_s_idx",
        ),
        migrations.RenameIndex(
            model_name="cdcconnection",
            new_name="voyant_cdc__workflo_734bd4_idx",
            old_name="voyant_cdc_workflo_idx",
        ),
    ]
