# Generated by Django 5.2.14 on 2026-09-09 16:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Target URL to receive POST requests", max_length=2048
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text='List of subscribed event types: ["job.completed", "pipeline.failed"]',
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Shared secret for HMAC-SHA256 signature verification",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "retry_policy",
                    models.JSONField(
                        default=dict,
                        help_text='Retry config: {"max_retries": 3, "initial_backoff_seconds": 1, "backoff_multiplier": 2}',
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional HTTP headers to include in delivery requests",
                    ),
                ),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last delivery attempt",
                        null=True,
                    ),
                ),
                (
                    "failure_count",
                    models.IntegerField(
                        default=0,
                        help_text="Consecutive failure count; auto-disabled after threshold",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "db_table": "voyant_webhook",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="voyant_webh_tenant__f74a67_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="Event type that triggered this delivery",
                        max_length=128,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Full event payload sent (or to be sent) to the endpoint",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of delivery attempts so far"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        default=3, help_text="Maximum retry attempts for this delivery"
                    ),
                ),
                (
                    "last_response_code",
                    models.IntegerField(
                        blank=True,
                        help_text="HTTP status code from the last attempt",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message from the last failed attempt",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when delivery succeeded",
                        null=True,
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        help_text="Parent webhook subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery",
                "verbose_name_plural": "Webhook Deliveries",
                "db_table": "voyant_webhook_delivery",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["webhook", "status"],
                        name="voyant_webh_webhook_af0209_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "event_type", "-created_at"],
                        name="voyant_webh_tenant__26441c_idx",
                    ),
                ],
            },
        ),
    ]
