# Generated by Django 5.2.17 on 2026-09-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feature",
            name="unique_feature_name_per_group",
        ),
        migrations.RemoveConstraint(
            model_name="featureversion",
            name="unique_feature_version_number",
        ),
        migrations.RemoveIndex(
            model_name="feature",
            name="feat_tenant_crt_asc_idx",
        ),
        migrations.RemoveIndex(
            model_name="featuregroup",
            name="feat_group_tenant_crt_asc_idx",
        ),
        migrations.RemoveIndex(
            model_name="featurevalue",
            name="fval_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="feature",
            new_name="feature_feature_173583_idx",
            old_name="feat_grp_name_idx",
        ),
        migrations.RenameIndex(
            model_name="feature",
            new_name="feature_tenant__2eaf45_idx",
            old_name="feat_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="featuregroup",
            new_name="feature_gro_tenant__ae632f_idx",
            old_name="feat_group_tenant_name_idx",
        ),
        migrations.RenameIndex(
            model_name="featuregroup",
            new_name="feature_gro_tenant__7d8fb1_idx",
            old_name="feat_group_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="featurevalue",
            new_name="feature_val_feature_70f861_idx",
            old_name="fval_feat_ent_computed_idx",
        ),
        migrations.RenameIndex(
            model_name="featurevalue",
            new_name="feature_val_tenant__ecd104_idx",
            old_name="fval_tenant_entity_idx",
        ),
        migrations.RenameIndex(
            model_name="featurevalue",
            new_name="feature_val_tenant__d2d05d_idx",
            old_name="fval_tenant_computed_idx",
        ),
        migrations.AlterUniqueTogether(
            name="feature",
            unique_together={("feature_group", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="featureversion",
            unique_together={("feature", "version_number")},
        ),
    ]
