# Generated by Django 6.0.2 on 2026-09-09 15:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SavedQuery",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the saved query",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description explaining the query's purpose",
                    ),
                ),
                ("query_text", models.TextField(help_text="The SQL query text")),
                (
                    "language",
                    models.CharField(
                        default="sql",
                        help_text="Query language (e.g., 'sql')",
                        max_length=32,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional parameter definitions for parameterized queries",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="If true, the query is visible to all users in the same tenant",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        db_index=True,
                        help_text="User ID of the query creator (from auth context)",
                        max_length=256,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Query",
                "verbose_name_plural": "Saved Queries",
                "db_table": "voyant_saved_query",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "created_by", "-updated_at"],
                        name="voyant_save_tenant__58da05_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "is_public", "-updated_at"],
                        name="voyant_save_tenant__d1a9c5_idx",
                    ),
                ],
            },
        ),
    ]
