# Generated by Django 6.0.2 on 2026-09-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedquery",
            name="shared_with",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of user IDs the query is explicitly shared with",
            ),
        ),
    ]
