# Generated by Django 5.2.17 on 2026-09-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="idx_comment_tenant_created",
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="idx_comment_realm_tenant",
        ),
        migrations.RemoveIndex(
            model_name="workspace",
            name="idx_ws_tenant_created",
        ),
        migrations.RemoveIndex(
            model_name="workspace",
            name="idx_ws_realm_tenant",
        ),
        migrations.RemoveIndex(
            model_name="workspaceasset",
            name="idx_wsa_tenant_created",
        ),
        migrations.RemoveIndex(
            model_name="workspaceasset",
            name="idx_wsa_realm_tenant",
        ),
        migrations.RemoveIndex(
            model_name="workspacemember",
            name="idx_wsm_tenant_created",
        ),
        migrations.RemoveIndex(
            model_name="workspacemember",
            name="idx_wsm_realm_tenant",
        ),
    ]
