# Generated by Django 5.2.16 on 2026-09-05 14:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique action type name", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Parameter definitions: [{"name": "reason", "type": "string", "required": true}, ...]',
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Pre-condition rules: [{"type": "status_check", "value": "open"}, ...]',
                    ),
                ),
                (
                    "side_effects",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Side effects: [{"type": "notification", "channel": "email"}, {"type": "webhook", "url": "..."}]',
                    ),
                ),
                (
                    "undoable",
                    models.BooleanField(
                        default=False, help_text="Whether this action supports undo"
                    ),
                ),
                (
                    "undo_rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Undo rules: [{"type": "status_revert"}, ...]',
                    ),
                ),
                (
                    "required_permission",
                    models.CharField(
                        blank=True,
                        help_text="Permission required to execute this action",
                        max_length=256,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "db_table": "ontology_action_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ObjectType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this object type within the namespace",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Human-readable description"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Auto-incrementing schema version"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Soft-deletion timestamp (null = active)",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "ontology_object_type",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "name"], name="idx_ot_tenant_name"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant_id", "name"),
                        name="uq_object_type_name_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        default=dict,
                        help_text="Key-value properties conforming to the object type schema",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Optimistic concurrency version"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Soft-deletion timestamp (null = active)",
                        null=True,
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        help_text="Schema this instance conforms to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="ontology.objecttype",
                    ),
                ),
            ],
            options={
                "db_table": "ontology_object",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LinkType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique link type name within the namespace",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "cardinality",
                    models.CharField(
                        choices=[
                            ("one_to_one", "One-to-One"),
                            ("one_to_many", "One-to-Many"),
                            ("many_to_many", "Many-to-Many"),
                        ],
                        default="one_to_many",
                        help_text="Cardinality of the relationship",
                        max_length=20,
                    ),
                ),
                (
                    "properties_schema",
                    models.JSONField(
                        blank=True,
                        help_text="JSON schema for optional properties on link instances",
                        null=True,
                    ),
                ),
                (
                    "inverse_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional name for the inverse traversal direction",
                        max_length=255,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Soft-deletion timestamp (null = active)",
                        null=True,
                    ),
                ),
                (
                    "source_object_type",
                    models.ForeignKey(
                        help_text="Source object type",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_link_types",
                        to="ontology.objecttype",
                    ),
                ),
                (
                    "target_object_type",
                    models.ForeignKey(
                        help_text="Target object type",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_link_types",
                        to="ontology.objecttype",
                    ),
                ),
            ],
            options={
                "db_table": "ontology_link_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Interface",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique interface name within the namespace",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "required_properties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of required property definitions: [{"name": "x", "type": "string"}, ...]',
                    ),
                ),
                (
                    "optional_properties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of optional property definitions: [{"name": "x", "type": "string"}, ...]',
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "implementing_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Object types that implement this interface",
                        related_name="interfaces",
                        to="ontology.objecttype",
                    ),
                ),
            ],
            options={
                "db_table": "ontology_interface",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Unique function name", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "language",
                    models.CharField(
                        choices=[("python", "Python"), ("typescript", "TypeScript")],
                        default="python",
                        max_length=20,
                    ),
                ),
                ("source_code", models.TextField(help_text="Function source code")),
                (
                    "entry_point",
                    models.CharField(
                        default="handler",
                        help_text="Entry point function name",
                        max_length=255,
                    ),
                ),
                (
                    "input_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Input parameter schema: {"params": [{"name": "x", "type": "integer"}]}',
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Output schema: {"type": "object", "properties": {...}}',
                    ),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(default=30, help_text="Max execution time"),
                ),
                (
                    "memory_limit_mb",
                    models.IntegerField(default=128, help_text="Max memory usage"),
                ),
                ("created_by", models.CharField(blank=True, max_length=256)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "attached_to_action",
                    models.ForeignKey(
                        blank=True,
                        help_text="Action type this function is attached to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="functions",
                        to="ontology.actiontype",
                    ),
                ),
                (
                    "attached_to_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Object type this function is attached to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="functions",
                        to="ontology.objecttype",
                    ),
                ),
            ],
            options={
                "db_table": "ontology_function",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="actiontype",
            name="target_object_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Object type this action operates on",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="action_types",
                to="ontology.objecttype",
            ),
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Property name (unique per object type)",
                        max_length=255,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("timestamp", "Timestamp"),
                            ("enum", "Enum"),
                            ("array", "Array"),
                            ("map", "Map"),
                            ("struct", "Struct"),
                            ("geopoint", "Geopoint"),
                        ],
                        help_text="Data type of this property",
                        max_length=32,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this property is required on instances",
                    ),
                ),
                (
                    "default_value",
                    models.JSONField(
                        blank=True, help_text="Default value (JSON-encoded)", null=True
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        help_text="Validation rules: regex, min, max, enum_values, custom",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary metadata (display_name, description, etc.)",
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        help_text="Parent object type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="ontology.objecttype",
                    ),
                ),
            ],
            options={
                "db_table": "ontology_property",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SharedProperty",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique shared property name", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("timestamp", "Timestamp"),
                            ("enum", "Enum"),
                            ("array", "Array"),
                            ("map", "Map"),
                            ("struct", "Struct"),
                            ("geopoint", "Geopoint"),
                        ],
                        help_text="Data type",
                        max_length=32,
                    ),
                ),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("validation_rules", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "used_by_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Object types that use this shared property",
                        related_name="shared_properties",
                        to="ontology.objecttype",
                    ),
                ),
            ],
            options={
                "db_table": "ontology_shared_property",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StructType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique struct type name", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "fields",
                    models.JSONField(
                        default=list,
                        help_text='List of fields: [{"name": "street", "type": "string", "required": true}, ...]',
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "db_table": "ontology_struct_type",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="ontology_st_tenant__0bb4bd_idx",
                    ),
                    models.Index(
                        fields=["realm", "tenant_id", "created_at"],
                        name="ontology_st_realm_deb5ff_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant_id", "name"),
                        name="uq_struct_type_name_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ValueType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique value type name", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "base_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("timestamp", "Timestamp"),
                            ("enum", "Enum"),
                            ("array", "Array"),
                            ("map", "Map"),
                            ("struct", "Struct"),
                            ("geopoint", "Geopoint"),
                        ],
                        help_text="Underlying property type",
                        max_length=32,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "constraints",
                    models.JSONField(
                        default=dict,
                        help_text='Constraints: {"regex": "...", "min": 0, "max": 100, "enum_values": [...]}',
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=256)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System value types cannot be deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "db_table": "ontology_value_type",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="ontology_va_tenant__b2ca9c_idx",
                    ),
                    models.Index(
                        fields=["realm", "tenant_id", "created_at"],
                        name="ontology_va_realm_528739_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant_id", "name"),
                        name="uq_value_type_name_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional properties on this link instance",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Soft-deletion timestamp (null = active)",
                        null=True,
                    ),
                ),
                (
                    "link_type",
                    models.ForeignKey(
                        help_text="Schema this link conforms to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="ontology.linktype",
                    ),
                ),
                (
                    "source_object",
                    models.ForeignKey(
                        help_text="Source object instance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="ontology.object",
                    ),
                ),
                (
                    "target_object",
                    models.ForeignKey(
                        help_text="Target object instance",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="ontology.object",
                    ),
                ),
            ],
            options={
                "db_table": "ontology_link",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["link_type_id"], name="idx_link_type"),
                    models.Index(fields=["source_object_id"], name="idx_link_source"),
                    models.Index(fields=["target_object_id"], name="idx_link_target"),
                    models.Index(
                        fields=["tenant_id", "link_type_id"],
                        name="idx_link_tenant_type",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("link_type_id", "source_object_id", "target_object_id"),
                        name="uq_link_instance_active",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="object",
            index=models.Index(fields=["object_type_id"], name="idx_obj_type"),
        ),
        migrations.AddIndex(
            model_name="object",
            index=models.Index(
                fields=["tenant_id", "object_type_id"], name="idx_obj_tenant_type"
            ),
        ),
        migrations.AddIndex(
            model_name="object",
            index=models.Index(
                fields=["tenant_id", "-created_at"], name="idx_obj_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="linktype",
            index=models.Index(fields=["tenant_id", "name"], name="idx_lt_tenant_name"),
        ),
        migrations.AddIndex(
            model_name="linktype",
            index=models.Index(fields=["source_object_type_id"], name="idx_lt_source"),
        ),
        migrations.AddIndex(
            model_name="linktype",
            index=models.Index(fields=["target_object_type_id"], name="idx_lt_target"),
        ),
        migrations.AddConstraint(
            model_name="linktype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "name"),
                name="uq_link_type_name_active",
            ),
        ),
        migrations.AddIndex(
            model_name="interface",
            index=models.Index(
                fields=["tenant_id", "name"], name="idx_iface_tenant_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="interface",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "name"),
                name="uq_interface_name_active",
            ),
        ),
        migrations.AddIndex(
            model_name="function",
            index=models.Index(
                fields=["tenant_id", "status"], name="idx_func_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="function",
            index=models.Index(
                fields=["attached_to_type_id"], name="idx_func_attached_type"
            ),
        ),
        migrations.AddIndex(
            model_name="function",
            index=models.Index(
                fields=["attached_to_action_id"], name="idx_func_attached_action"
            ),
        ),
        migrations.AddConstraint(
            model_name="function",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "name"),
                name="uq_function_name_active",
            ),
        ),
        migrations.AddIndex(
            model_name="actiontype",
            index=models.Index(
                fields=["tenant_id", "status"], name="idx_action_tenant_status"
            ),
        ),
        migrations.AddIndex(
            model_name="actiontype",
            index=models.Index(
                fields=["target_object_type_id"], name="idx_action_target_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="actiontype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "name"),
                name="uq_action_type_name_active",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["object_type_id"], name="idx_prop_object_type"),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.UniqueConstraint(
                fields=("object_type_id", "name"), name="uq_property_name_per_type"
            ),
        ),
        migrations.AddIndex(
            model_name="sharedproperty",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="ontology_sh_tenant__9327ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sharedproperty",
            index=models.Index(
                fields=["realm", "tenant_id", "created_at"],
                name="ontology_sh_realm_4b4d68_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharedproperty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant_id", "name"),
                name="uq_shared_prop_name_active",
            ),
        ),
    ]
