# Generated by Django 5.2.16 on 2026-09-07 15:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0001_add_v4_ontology_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionExecution",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "previous_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of object properties before execution (for undo)",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Diff of changes applied during execution",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("undone", "Undone"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("actor", models.CharField(blank=True, default="", max_length=256)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "action_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="ontology.actiontype",
                    ),
                ),
                (
                    "target_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="action_executions",
                        to="ontology.object",
                    ),
                ),
            ],
            options={
                "db_table": "ontology_action_execution",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "action_type_id"],
                        name="idx_exec_tenant_action",
                    ),
                    models.Index(
                        fields=["tenant_id", "target_object_id"],
                        name="idx_exec_tenant_obj",
                    ),
                ],
            },
        ),
    ]
