# Generated by Django 5.2.17 on 2026-09-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0005_piidetection_qualityscore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="piidetection",
            options={},
        ),
        migrations.AlterModelOptions(
            name="qualityscore",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="piidetection",
            name="idx_pii_tenant_created",
        ),
        migrations.RemoveIndex(
            model_name="piidetection",
            name="idx_pii_realm_tenant",
        ),
        migrations.RemoveIndex(
            model_name="qualityscore",
            name="idx_qs_tenant_created",
        ),
        migrations.RemoveIndex(
            model_name="qualityscore",
            name="idx_qs_realm_tenant",
        ),
    ]
