# Generated by Django 6.0.2 on 2026-09-11 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontology", "0006_alter_piidetection_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectTypeGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Group name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Group description"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color for visual identification (e.g. #FF4D00)",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon identifier (e.g. emoji or icon name)",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order for display"
                    ),
                ),
                (
                    "object_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Object types belonging to this group",
                        related_name="groups",
                        to="ontology.objecttype",
                    ),
                ),
            ],
            options={
                "db_table": "ontology_object_type_group",
                "ordering": ["order", "name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="ontology_ob_tenant__579890_idx",
                    ),
                    models.Index(
                        fields=["realm", "tenant_id", "created_at"],
                        name="ontology_ob_realm_a45ac0_idx",
                    ),
                ],
            },
        ),
    ]
