# Trino PostgreSQL Catalog
connector.name=postgresql
connection-url=${TRINO_POSTGRES_CONNECTION_URL}
connection-user=${TRINO_POSTGRES_CONNECTION_USER}
connection-password=${TRINO_POSTGRES_CONNECTION_PASSWORD}
