# Generated by Django 5.2.16 on 2026-09-05 15:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Provider name (e.g. 'Groq', 'MiMo')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (e.g. 'groq', 'mimo')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "api_base_url",
                    models.CharField(
                        help_text="OpenAI-compatible API base URL", max_length=500
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key (encrypted in Vault)",
                        max_length=500,
                    ),
                ),
                (
                    "api_key_vault_path",
                    models.CharField(
                        blank=True, help_text="Vault path for API key", max_length=255
                    ),
                ),
                ("supports_chat", models.BooleanField(default=True)),
                ("supports_streaming", models.BooleanField(default=True)),
                ("supports_json_mode", models.BooleanField(default=False)),
                ("supports_function_calling", models.BooleanField(default=False)),
                ("supports_vision", models.BooleanField(default=False)),
                ("supports_embeddings", models.BooleanField(default=False)),
                (
                    "default_headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Extra headers: {"X-Custom": "value"}',
                    ),
                ),
                (
                    "rate_limit_rpm",
                    models.IntegerField(
                        default=0, help_text="Requests per minute (0 = unlimited)"
                    ),
                ),
                ("timeout_seconds", models.IntegerField(default=30)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System providers cannot be deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "llm_provider",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Model ID (e.g. 'openai/gpt-oss-120b')",
                        max_length=200,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, help_text="Human-readable name", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "context_window",
                    models.IntegerField(default=4096, help_text="Max context tokens"),
                ),
                (
                    "max_output_tokens",
                    models.IntegerField(
                        default=4096, help_text="Max completion tokens"
                    ),
                ),
                ("supports_vision", models.BooleanField(default=False)),
                ("supports_function_calling", models.BooleanField(default=False)),
                ("supports_json_mode", models.BooleanField(default=False)),
                (
                    "supports_reasoning",
                    models.BooleanField(
                        default=False, help_text="Supports reasoning/chain-of-thought"
                    ),
                ),
                (
                    "input_price",
                    models.FloatField(
                        default=0.0, help_text="Price per 1M input tokens ($)"
                    ),
                ),
                (
                    "output_price",
                    models.FloatField(
                        default=0.0, help_text="Price per 1M output tokens ($)"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default model for this provider"
                    ),
                ),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("avg_latency_ms", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="llm_providers.llmprovider",
                    ),
                ),
            ],
            options={
                "db_table": "llm_model",
                "ordering": ["provider", "name"],
                "unique_together": {("provider", "name")},
            },
        ),
        migrations.CreateModel(
            name="ActiveLLMConfig",
            fields=[
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("intent", "Intent Engine"),
                            ("analysis", "Data Analysis"),
                            ("scraper", "Scraper AI"),
                            ("general", "General"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("temperature", models.FloatField(default=0.1)),
                ("max_tokens", models.IntegerField(default=4096)),
                ("timeout_seconds", models.IntegerField(default=30)),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="llm_providers.llmmodel",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="llm_providers.llmprovider",
                    ),
                ),
            ],
            options={
                "db_table": "llm_active_config",
            },
        ),
    ]
