# Generated by Django 5.2.16 on 2026-09-05 14:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("artifact_location", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "db_table": "ml_experiment",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="ml_experime_tenant__670ac0_idx",
                    ),
                    models.Index(
                        fields=["realm", "tenant_id", "created_at"],
                        name="ml_experime_realm_31e52c_idx",
                    ),
                ],
                "unique_together": {("tenant_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="RegisteredModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ml_registered_model",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="ml_register_tenant__c55d95_idx",
                    ),
                    models.Index(
                        fields=["realm", "tenant_id", "created_at"],
                        name="ml_register_realm_39610c_idx",
                    ),
                ],
                "unique_together": {("tenant_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                            ("killed", "Killed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True, default=dict, help_text="Hyperparameters"
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, default=dict, help_text="Evaluation metrics"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="ml_platform.experiment",
                    ),
                ),
            ],
            options={
                "db_table": "ml_run",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="ready", max_length=20)),
                ("storage_path", models.CharField(blank=True, max_length=512)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "registered_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="ml_platform.registeredmodel",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ml_platform.run",
                    ),
                ),
            ],
            options={
                "db_table": "ml_model_version",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RunArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("model", "Model"),
                            ("dataset", "Dataset"),
                            ("image", "Image"),
                            ("metric", "Metric"),
                            ("log", "Log"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("storage_path", models.CharField(max_length=512)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="ml_platform.run",
                    ),
                ),
            ],
            options={
                "db_table": "ml_run_artifact",
            },
        ),
        migrations.CreateModel(
            name="ModelEndpoint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="inactive",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Endpoint config: {"timeout_ms": 5000, "max_batch_size": 32}',
                    ),
                ),
                ("endpoint_path", models.CharField(blank=True, max_length=255)),
                ("invocation_count", models.PositiveIntegerField(default=0)),
                ("avg_latency_ms", models.FloatField(default=0.0)),
                (
                    "model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ml_platform.modelversion",
                    ),
                ),
            ],
            options={
                "db_table": "ml_model_endpoint",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="ml_model_en_tenant__8bf815_idx",
                    ),
                    models.Index(
                        fields=["realm", "tenant_id", "created_at"],
                        name="ml_model_en_realm_34e5f2_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["experiment_id", "status"], name="ml_run_experim_dedbc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["tenant_id", "-started_at"], name="ml_run_tenant__dddeda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="ml_model_ve_tenant__b0514f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["realm", "tenant_id", "created_at"],
                name="ml_model_ve_realm_88276a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modelversion",
            unique_together={("registered_model_id", "version")},
        ),
    ]
