# Generated by Django 5.2.16 on 2026-09-07 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_platform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentDefinition",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(help_text="System prompt for the agent"),
                ),
                (
                    "model_provider",
                    models.CharField(
                        default="groq", help_text="LLM provider", max_length=100
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="openai/gpt-oss-120b",
                        help_text="Model identifier",
                        max_length=255,
                    ),
                ),
                ("temperature", models.FloatField(default=0.1)),
                ("max_tokens", models.IntegerField(default=4096)),
                (
                    "tools",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of allowed MCP tools: ["voyant.sql", "voyant.search", ...]',
                    ),
                ),
                (
                    "guardrails",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Safety rules: {"max_queries_per_session": 50, "blocked_tables": [], "require_approval": false}',
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ml_agent_definition",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="ml_agent_de_tenant__e05322_idx",
                    ),
                    models.Index(
                        fields=["realm", "tenant_id", "created_at"],
                        name="ml_agent_de_realm_9be790_idx",
                    ),
                ],
                "unique_together": {("tenant_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="AgentEvaluation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "test_cases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"input": "query", "expected": "answer", "tools_used": ["voyant.sql"]}]',
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"input": "...", "output": "...", "score": 0.95, "judge_notes": "..."}]',
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        blank=True, help_text="0.0-1.0 aggregate score", null=True
                    ),
                ),
                (
                    "judge_model",
                    models.CharField(
                        default="openai/gpt-oss-120b",
                        help_text="AI judge model",
                        max_length=255,
                    ),
                ),
                ("run_count", models.PositiveIntegerField(default=0)),
                ("passed_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="ml_platform.agentdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "ml_agent_evaluation",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="ml_agent_ev_tenant__48e5ea_idx",
                    ),
                    models.Index(
                        fields=["realm", "tenant_id", "created_at"],
                        name="ml_agent_ev_realm_63979d_idx",
                    ),
                ],
            },
        ),
    ]
