# Generated by Django 6.0 on 2026-02-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="scrapejob",
            new_name="voyant_scra_tenant__759caa_idx",
            old_name="voyant_scra_tenant__e7c5e0_idx",
        ),
        migrations.RenameIndex(
            model_name="scrapejob",
            new_name="voyant_scra_created_1db6a5_idx",
            old_name="voyant_scra_created_7c2346_idx",
        ),
    ]
