# Generated by Django 5.2.16 on 2026-09-05 14:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scraper",
            "0002_rename_voyant_scra_tenant__e7c5e0_idx_voyant_scra_tenant__759caa_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(db_index=True, default="system", max_length=128),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "site_pattern",
                    models.CharField(help_text="URL pattern or domain", max_length=500),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ecommerce", "E-Commerce"),
                            ("social", "Social Media"),
                            ("maps", "Maps"),
                            ("news", "News"),
                            ("finance", "Finance"),
                            ("jobs", "Jobs"),
                            ("realestate", "Real Estate"),
                            ("travel", "Travel"),
                            ("education", "Education"),
                            ("developer", "Developer"),
                            ("leadgen", "Lead Generation"),
                            ("directory", "Directory"),
                            ("search", "Search Engine"),
                            ("universal", "Universal"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=20),
                ),
                ("engine", models.CharField(default="playwright", max_length=20)),
                ("selectors", models.JSONField(default=dict)),
                ("workflow", models.JSONField(default=list)),
                ("options", models.JSONField(default=dict)),
                ("parameters", models.JSONField(default=list)),
                ("output_fields", models.JSONField(default=list)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "scraper_template",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "category"],
                        name="scraper_tem_tenant__cdfb58_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "status"],
                        name="scraper_tem_tenant__aeffb7_idx",
                    ),
                    models.Index(
                        fields=["site_pattern"], name="scraper_tem_site_pa_a6600b_idx"
                    ),
                ],
            },
        ),
    ]
