# Generated by Django 6.0.2 on 2026-09-09 00:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0003_add_scrape_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSkill",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique skill name identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of what this skill does",
                    ),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of step definitions for this skill",
                    ),
                ),
                (
                    "tools",
                    models.JSONField(
                        default=list,
                        help_text="List of MCP tool names this skill can invoke",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="JSON Schema defining parameters this skill accepts",
                    ),
                ),
            ],
            options={
                "db_table": "voyant_agent_skill",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeFingerprint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        help_text="User-Agent string for the browser context"
                    ),
                ),
                (
                    "viewport_width",
                    models.PositiveIntegerField(
                        default=1920, help_text="Browser viewport width in pixels"
                    ),
                ),
                (
                    "viewport_height",
                    models.PositiveIntegerField(
                        default=1080, help_text="Browser viewport height in pixels"
                    ),
                ),
                (
                    "webgl_vendor",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="WebGL vendor string (e.g., 'Google Inc. (NVIDIA)')",
                        max_length=255,
                    ),
                ),
                (
                    "webgl_renderer",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="WebGL renderer string (e.g., 'ANGLE (NVIDIA GeForce GTX 1080 ...)')",
                    ),
                ),
            ],
            options={
                "db_table": "voyant_scrape_fingerprint",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeExport",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("xlsx", "XLSX"),
                            ("xml", "XML"),
                            ("jsonl", "JSONL"),
                            ("parquet", "Parquet"),
                        ],
                        default="json",
                        help_text="Export file format",
                        max_length=16,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        help_text="Export destination (S3 path, webhook URL, file path)",
                        max_length=1024,
                    ),
                ),
                (
                    "auto_export",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically export after each task run",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="scraper.scrapejob",
                    ),
                ),
            ],
            options={
                "db_table": "voyant_scrape_export",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeProxy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proxy_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("datacenter", "Datacenter"),
                            ("mobile", "Mobile"),
                            ("isp", "ISP"),
                        ],
                        db_index=True,
                        default="residential",
                        max_length=32,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Proxy provider (e.g., brightdata, oxylabs, smartproxy)",
                        max_length=128,
                    ),
                ),
                (
                    "endpoints",
                    models.JSONField(
                        default=list, help_text="List of proxy gateway URLs"
                    ),
                ),
                (
                    "rotation_strategy",
                    models.CharField(
                        choices=[
                            ("per_request", "Per Request"),
                            ("session", "Session-Based"),
                            ("sticky", "Sticky"),
                        ],
                        default="per_request",
                        max_length=32,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this proxy configuration is currently active",
                    ),
                ),
            ],
            options={
                "db_table": "voyant_scrape_proxy",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["proxy_type", "is_active"],
                        name="voyant_scra_proxy_t_960066_idx",
                    ),
                    models.Index(
                        fields=["provider", "is_active"],
                        name="voyant_scra_provide_d846a2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScrapeWorkflow",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Workflow name", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "steps",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of step definitions (JSON array)",
                    ),
                ),
                (
                    "input_schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON Schema defining expected input parameters",
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        default=dict, help_text="JSON Schema defining output structure"
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
            ],
            options={
                "db_table": "voyant_scrape_workflow",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="voyant_scra_tenant__d1a16a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScrapeStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Execution order within the workflow"
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("navigate", "Navigate"),
                            ("click", "Click"),
                            ("scroll", "Scroll"),
                            ("wait", "Wait"),
                            ("extract", "Extract"),
                            ("enter_text", "Enter Text"),
                            ("hover", "Hover"),
                            ("screenshot", "Screenshot"),
                            ("loop", "Loop"),
                            ("condition", "Condition"),
                            ("close_popup", "Close Popup"),
                            ("back", "Back"),
                            ("new_tab", "New Tab"),
                            ("download", "Download"),
                        ],
                        help_text="Type of action this step performs",
                        max_length=32,
                    ),
                ),
                (
                    "selector",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CSS selector or XPath for the target element",
                        max_length=1024,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Action identifier or label for this step",
                        max_length=255,
                    ),
                ),
                (
                    "wait_condition",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Condition to wait for before executing (CSS selector or timeout)",
                        max_length=512,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        default=dict,
                        help_text="Step-specific configuration (e.g., wait_ms, times, text)",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_records",
                        to="scraper.scrapeworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "voyant_scrape_step",
                "ordering": ["workflow", "order"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=32,
                    ),
                ),
                (
                    "rows_extracted",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of data rows extracted in this run"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total execution duration in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Distributed tracing ID (e.g., OpenTelemetry trace ID)",
                        max_length=128,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this run actually started executing",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this run completed (success, failure, or cancellation)",
                        null=True,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="scraper.scrapejob",
                    ),
                ),
            ],
            options={
                "db_table": "voyant_scrape_run",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "-created_at"],
                        name="voyant_scra_task_id_20f1ea_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="voyant_scra_status_ed4c9a_idx",
                    ),
                    models.Index(
                        fields=["trace_id"], name="voyant_scra_trace_i_812523_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScrapeSchedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cron_expr",
                    models.CharField(
                        help_text="Cron expression (e.g., '0 8 * * *' for daily at 8am)",
                        max_length=128,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for cron schedule (e.g., 'America/New_York')",
                        max_length=64,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this schedule is active",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="scraper.scrapejob",
                    ),
                ),
            ],
            options={
                "db_table": "voyant_scrape_schedule",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["enabled", "-created_at"],
                        name="voyant_scra_enabled_8ae8f0_idx",
                    )
                ],
            },
        ),
    ]
