# Generated by Django 6.0.2 on 2026-09-09 00:58

from django.db import migrations, models


def populate_tenant_id(apps, schema_editor):
    """Set default tenant_id on existing rows (if any)."""
    for model_name in [
        "ScrapeSchedule",
        "ScrapeExport",
        "ScrapeRun",
        "ScrapeProxy",
        "ScrapeFingerprint",
        "AgentSkill",
    ]:
        Model = apps.get_model("scraper", model_name)
        Model.objects.filter(tenant_id__isnull=True).update(tenant_id="default")
        Model.objects.filter(tenant_id="").update(tenant_id="default")


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0004_agentskill_scrapefingerprint_scrapeexport_and_more"),
    ]

    operations = [
        # ── ScrapeWorkflow: already has tenant_id, add realm ──────────────
        migrations.AddField(
            model_name="scrapeworkflow",
            name="realm",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Realm identifier for RBAC realm isolation",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="scrapeworkflow",
            index=models.Index(
                fields=["realm", "tenant_id", "created_at"],
                name="voyant_scwf_realm_tenant_idx",
            ),
        ),
        # ── ScrapeSchedule: add realm + tenant_id ─────────────────────────
        migrations.AddField(
            model_name="scrapeschedule",
            name="realm",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Realm identifier for RBAC realm isolation",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="scrapeschedule",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="scrapeschedule",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="voyant_scsch_tenant_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapeschedule",
            index=models.Index(
                fields=["realm", "tenant_id", "created_at"],
                name="voyant_scsch_realm_tenant_idx",
            ),
        ),
        # ── ScrapeExport: add realm + tenant_id ───────────────────────────
        migrations.AddField(
            model_name="scrapeexport",
            name="realm",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Realm identifier for RBAC realm isolation",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="scrapeexport",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="scrapeexport",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="voyant_scexp_tenant_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapeexport",
            index=models.Index(
                fields=["realm", "tenant_id", "created_at"],
                name="voyant_scexp_realm_tenant_idx",
            ),
        ),
        # ── ScrapeRun: add realm + tenant_id ──────────────────────────────
        migrations.AddField(
            model_name="scraperun",
            name="realm",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Realm identifier for RBAC realm isolation",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="scraperun",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="scraperun",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="voyant_scrun_tenant_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scraperun",
            index=models.Index(
                fields=["realm", "tenant_id", "created_at"],
                name="voyant_scrun_realm_tenant_idx",
            ),
        ),
        # ── ScrapeProxy: add realm + tenant_id ────────────────────────────
        migrations.AddField(
            model_name="scrapeproxy",
            name="realm",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Realm identifier for RBAC realm isolation",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="scrapeproxy",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="scrapeproxy",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="voyant_scprx_tenant_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapeproxy",
            index=models.Index(
                fields=["realm", "tenant_id", "created_at"],
                name="voyant_scprx_realm_tenant_idx",
            ),
        ),
        # ── ScrapeFingerprint: add realm + tenant_id ──────────────────────
        migrations.AddField(
            model_name="scrapefingerprint",
            name="realm",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Realm identifier for RBAC realm isolation",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="scrapefingerprint",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="scrapefingerprint",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="voyant_scfp_tenant_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapefingerprint",
            index=models.Index(
                fields=["realm", "tenant_id", "created_at"],
                name="voyant_scfp_realm_tenant_idx",
            ),
        ),
        # ── AgentSkill: add realm + tenant_id ─────────────────────────────
        migrations.AddField(
            model_name="agentskill",
            name="realm",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Realm identifier for RBAC realm isolation",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="agentskill",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="agentskill",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="voyant_askill_tenant_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentskill",
            index=models.Index(
                fields=["realm", "tenant_id", "created_at"],
                name="voyant_askill_realm_tenant_idx",
            ),
        ),
    ]
