# Generated by Django 6.0.2 on 2026-09-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0005_add_tenant_fields_to_v4_models"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="agentskill",
            name="voyant_askill_tenant_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="agentskill",
            name="voyant_askill_realm_tenant_idx",
        ),
        migrations.RemoveIndex(
            model_name="scrapeexport",
            name="voyant_scexp_tenant_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="scrapeexport",
            name="voyant_scexp_realm_tenant_idx",
        ),
        migrations.RemoveIndex(
            model_name="scrapefingerprint",
            name="voyant_scfp_tenant_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="scrapefingerprint",
            name="voyant_scfp_realm_tenant_idx",
        ),
        migrations.RemoveIndex(
            model_name="scrapeproxy",
            name="voyant_scprx_tenant_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="scrapeproxy",
            name="voyant_scprx_realm_tenant_idx",
        ),
        migrations.RemoveIndex(
            model_name="scraperun",
            name="voyant_scrun_tenant_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="scraperun",
            name="voyant_scrun_realm_tenant_idx",
        ),
        migrations.RemoveIndex(
            model_name="scrapeschedule",
            name="voyant_scsch_tenant_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="scrapeschedule",
            name="voyant_scsch_realm_tenant_idx",
        ),
        migrations.RemoveIndex(
            model_name="scrapeworkflow",
            name="voyant_scra_tenant__d1a16a_idx",
        ),
        migrations.RemoveIndex(
            model_name="scrapeworkflow",
            name="voyant_scwf_realm_tenant_idx",
        ),
        migrations.AlterField(
            model_name="agentskill",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="scrapeexport",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="scrapefingerprint",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="scrapeproxy",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="scraperun",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="scrapeschedule",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="scrapeworkflow",
            name="tenant_id",
            field=models.CharField(
                db_index=True,
                help_text="Tenant identifier for multi-tenancy isolation",
                max_length=128,
            ),
        ),
    ]
