# Generated by Django 5.0.6 on 2026-05-22 09:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source_type", models.CharField(max_length=128)),
                ("status", models.CharField(default="pending", max_length=64)),
                ("connection_config", models.JSONField()),
                ("credentials", models.JSONField(blank=True, null=True)),
                (
                    "sync_schedule",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "datahub_urn",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
            ],
            options={
                "db_table": "voyant_source",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceDefinition",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "realm",
                    models.CharField(
                        db_index=True,
                        default="default",
                        help_text="Realm identifier for RBAC realm isolation",
                        max_length=64,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="Tenant identifier for multi-tenancy isolation",
                        max_length=128,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique name for the service",
                        max_length=255,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="Base URL where the service can be accessed",
                        max_length=512,
                    ),
                ),
                (
                    "spec_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the service's OpenAPI specification",
                        max_length=512,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", help_text="Service API version", max_length=64
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of the service",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        default="unknown",
                        help_text="Team or individual responsible for the service",
                        max_length=255,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="List of tags for categorizing the service",
                    ),
                ),
                (
                    "endpoints",
                    models.JSONField(
                        default=list,
                        help_text="List of API endpoints extracted from OpenAPI spec",
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        default="none",
                        help_text="Authentication type (e.g., OAuth2, Bearer, ApiKey)",
                        max_length=64,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata about the service"
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when service was first discovered",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when service was last seen or updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Definition",
                "verbose_name_plural": "Service Definitions",
                "db_table": "voyant_service_definition",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "name"],
                        name="voyant_serv_tenant__b959dd_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "-last_seen"],
                        name="voyant_serv_tenant__c5b811_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="servicedefinition",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "name"), name="unique_service_name_per_tenant"
            ),
        ),
    ]
