# Generated by Django 5.2.17 on 2026-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="idx_notif_tenant_created",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="idx_notif_realm_tenant",
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="voyant_noti_tenant__750526_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=["realm", "tenant_id", "created_at"],
                name="voyant_noti_realm_42bf0f_idx",
            ),
        ),
    ]
